UKHomeOffice/cerberus-service

src/forms/FieldSelect.jsx
src/govuk/Select.jsx
src/routes/IssueTargetPage.jsx

Add select element compatible with GDS specification.
2. Check if the select field looks like the field from GOV.UK Design System: https://design-system.service.gov.uk/components/select/
\* Required

COP-4093: Add select field compatible with GDS

---

src/govuk/Details.jsx
src/govuk/FormGroup.jsx
src/govuk/__tests__/Details.test.jsx
src/routes/IssueTargetPage.jsx

Add Details component compatible with GOV.UK Design System.
1. Open the `Issue a target form`
2. You should see a details component with summary `How to find the port from the dropdown list`
3. It should open and close
\* Required

COP-4093: Add Details component

---

src/forms/FieldDate.jsx
src/forms/FieldInput.jsx
src/forms/__tests__/FieldDate.test.jsx
src/forms/useField.js
src/forms/validators.js
src/govuk/DateInput.jsx
src/govuk/FormGroup.jsx
src/govuk/Input.jsx
src/govuk/Radios.jsx
src/govuk/Select.jsx
src/govuk/__tests__/DateInput.test.jsx
src/routes/IssueTargetPage.jsx

Add Date input component compatible with GOV.UK Design System.
1. Open the `Issue a target form`
2. You should see a date field
3. Entering an invalid or empty date should show an error
\* Required

COP-4093: Add FieldDate component

---

README.md
cypress/integration/cerberus/task-management.spec.js
cypress/plugins/index.js
cypress/support/commands.js

This PR has tests for verifying task management page. It checks all the available tabs & navigating to different page.
choose the spec to run
\* Required

COP-5461: Add tests for task management page

---

src/routes/TaskDetailsPage.jsx

Update buttons to match latest prototype
- now three buttons, a primary, a secondary, and a warning
- order of buttons changed to be `Issue target`, `Assessment complete`, `Dismiss`
- 'do not load' button removed
- open Cerberus locally
- go to `Tasks`
- click on a `Task`
- you should see button that match the prototype https://cerberus.prototype.cop.homeoffice.gov.uk/blue/pinned/task-detail
\* Required

COP-5896 Update buttons to match latest prototype

---

cypress/integration/cerberus/task-management.spec.js

This PR has tests for following scenarios,
1. Tasks refresh at 60 seconds
go to /tasks
after 60 seconds the list should refresh
after another 60 seconds the list should refresh again
(this can be seen in the network tab if there are no new tasks coming in)
2. User is kept on the page they are on
go to /tasks
go to page 2
after 60 seconds the list should refresh and user should still be on page 2 (url and pagination)
(this can be seen in the network tab if there are no new tasks coming in)
run test it('Should verify refresh task list page') in task-management.spec.js
\* Required

COP-5754: Add tests for Refresh tasklist page

---

src/routes/TaskDetailsPage.jsx

Add conditional logic to choose whether or not to render the notes form to the user. If the user is not assigned to any task in the `taskVersions` array, they are not able to see the notes form. If they are assigned to any task in the `taskVersions` array, they are able to see the notes form.
- Navigate to task where you are not assigned to it
- *You should not see the notes form*
- Claim the task
- *You should see the notes form*
- Input data into the notes form and submit
- *The form should submit successfully*
- *You should see the notes form appear again after submission*
\* Required

COP-5053 Add conditional for rendering notes form to user

---

.drone.yml
nginx/nginx.conf

Need to test this fix in dev, the changes are done so as detailed in this SO thread - https://stackoverflow.com/questions/24453388/nginx-reverse-proxy-causing-504-gateway-timeout/36589120#36589120
Temporarily commented out the `run_test_dev` step of the `drone.yml` in order to test changes to the nginx config file. After these changes have been tested, the test will be re-commented back
- Has to be deployed to dev in order to check if this fix prevents the time out issue
\* Required

Clear connection header

---

.eslintrc.js
cypress.json
cypress/config/dev.json
cypress/config/local.json
cypress/integration/cerberus/login.spec.js
cypress/integration/cerberus/task-management.spec.js
cypress/support/commands.js

Added tests for tasks notes functionality and it would cover the following scenarios,
Scenario 1: Assignee action
GIVEN I am assigned to a task
WHEN I view the task
THEN I am able to enter notes against the task and save them
Scenario 1: Non-assignee action
GIVEN I am NOT assigned to a task
WHEN I view the task
THEN I am NOT able to enter notes against the task
select task-management.spec.js and run the tests
\* Required

COP-5053: Add tests for task notes functionality

---

package-lock.json
package.json
src/routes/IssueTargetPage.jsx
src/routes/TaskDetailsPage.jsx

This PR removes the existing `@digitalpatterns/formio-gds-template` package and replaces it with the `@ukhomeoffice/formio-gds-template` package
- Open the `Issue a target` form
- *You should see the form render as before the changed package*
\* Required

COP-6243 Migrate formio-gds-template from digital patterns to homeoffice package

---

src/routes/IssueTargetPage.jsx

task submission now uses the businessKey generated by the form api service to set the businessKey of the process instance; fixing the breaking bug that had the static key as a temporary fix.
-Create a target in one of the non-implemented modes ( due to other bug in other ticket)
-see businessKey on form and note it down
-submit target
-check cop ui cockpit for businessKey and find task successfully created on cop-ui note it won't appear in team task until groups are implemented.
\* Required
No new tests needed, integration only, formio tests for the form have been updated

Update manual target submission to use dynamic businessKey

---

cypress/integration/cerberus/task-details.spec.js
cypress/integration/cerberus/task-management.spec.js
cypress/support/commands.js

Tests added for Unclaim task from Task management and Task details page.
run task-details.spec.js & task-management.spec.js 
\* Required

COP-6257: Add tests for Unclaim tasks from task management and task details page

---

.drone.yml

As a temporary measure, the tests that run against the dev environment as part of drone have been removed
NGINX seems to be bringing the Dev environment to its knees, which means that with every PR the drone build triggers the E2E tests on the Dev environment and since it might be down at the time of running the tests will fail.
With that said as a temporary measure, the E2E tests that run against the Dev environment as part of drone have been removed
from drone until the NGINX configurations gets sorted.
\* Required

Remove dev tests in drone.yml

---

src/utils/keycloak.jsx

When the keycloak token expires, a request is made to see if the access token can be updated. If not, the user is logged out. The recommended implementation of token refreshing is to use `onTokenExpired` as detailed in the `keycloak` documentation however, this led to inconsistencies as to when the token was identified as expired. 
- (Have dev tools open pre-emptively for testing)
- Pull and run cerberus natively
- Navigate to network tab in dev tools
- *You should see a `token` request made*
- Wait for as long as the access token is valid
- *You should see another `token` request made at the end of the access token's life span*
- Leave cerberus open for as long as the `refreshToken` is valid plus or minus the access token's life span
- *You should be logged out*
\* Required

COP-6242 Implement refresh token functionality

---

nginx/nginx.conf

Currently on Dev environment, the NGINX will resolve the IP address once, and keep it cached for subsequent requests until the configuration is reloaded.
This commit tells NGINX to use a name server to re-resolve the domain once the cached entry expires.
* go to https://www.dev.cerberus.cop.homeoffice.gov.uk/
* wait to see if you get a 503 or 504 error
\* Required

Update NGINX to re-resolve the domain name upon expiry

---

src/components/RenderForm.jsx
src/routes/IssueTargetPage.jsx
src/routes/TaskDetailsPage.jsx
src/routes/__tests__/TaskDetailsPage.test.jsx

When `currentUser` is the same as task `assignedUser`
- show the `Issue target button`
- on button click open the `Target Information Sheet form` and prefill it with the task details that are available
- create yourself a target task
- go to task list
- claim the task
- go to task details
- click on Issue target button
- > you should see the left hand panel be replaced with the Target Information Sheet form
- review the form
- > you should see some fields populated, based on what was in the task data
- > you will not see Mode or Port populated due to a bug in the data we receive from Camunda (Mark G working on this)
- submit the form (populate any required fields if needed)
- > you should see a success page
- click finish button
- > you should remain on task details page, and the main …

COP-5080 Add click functionality for issue target button

---

src/routes/TaskDetailsPage.jsx
src/routes/__tests__/TaskDetailsPage.test.jsx

Change the notes component to use the non interrupting event sub-process so that activity logs can be shown across task Id's and after the task is completed (future story requirements).  
Run Camunda-Cereberus locally and populate with RBT generated tasks via postman using branch COP-5769 (other PR)
Deploy raise-movement and assign-a-target
Run Cerberus-Service locally
Populate Camunda with an RBT generated task via postman to raise-movement
Open task details page
Submit a note
Refresh the page
See the note in date order following similar style to the rest
\* Required

COP-5769 Update notes component to show logs across task ID's and after task is completed

---

src/routes/TaskDetailsPage.jsx
src/routes/__tests__/TaskDetailsPage.test.jsx

Tidying up code so that the `camundaClient` and `useKeycloak` var are created in the components in which they're used, rather than being attached to the props.
Added mocked test data for TargetInformationSheet
- run Cerberus
- go to task details page
- check you can create a note (remember you must refresh to see it in activity list)
- check you can issue a target via the button
- check you can dismiss task
- check you can complete assessment on task
\* Required

Refactor variables

---

src/routes/TaskDetailsPage.jsx

Switch note submission to use the message wrapper BPMN
   
Note this commit requires the bpmn from https://gitlab.digital.homeoffice.gov.uk/cop/process-models/-/merge_requests/340
to be deployed to function.
 
Chose to use the existing form submission function, this does not appear to have broken any tests.
 
- deploy note-submission-wrapper.bpmn from https://gitlab.digital.homeoffice.gov.uk/cop/process-models/-/merge_requests/340 to cerberus-camunda
- create a new task as if from RBT via postman
- claim the task and go to the task details page
- submit a note
- refresh the page
- observe improved performance
 
 
\* Required
 
 
 
 

Expedite notes

---

jest.setup.jsx
src/components/ClaimTaskButton.jsx
src/components/__tests__/ClaimTaskButton.test.jsx

redirect user to `TaskDetailsPage` when they click 'claim' from the `TaskListPage`
Scenario One
- go to task list
- go to new tab
- click `claim`
- you should be taken to the TaskDetailsPage and see a task with an `unclaim` link
- go back to task list
- go to in progress tab
- find the task by it's businessKey (you might need to go to page 2+ to find it due to sort order)
Scenario Two
- go to task list
- go to new tab
- click on task title
- you should be taken to the TaskDetailsPage and see a task with a `claim` link
- click `claim`
- you should remain on TaskDetailsPage and it will refresh and the link changed to `unclaim`
- go back to task list
- go to in progress tab
- find the task by it's businessKey (you might need to go to page 2+ to find it due to sort order)
\* Required

COP-6431 Claim behaviour

---

src/components/ClaimTaskButton.jsx
src/routes/TaskDetails/TaskDetailsPage.jsx
src/routes/TaskLists/TaskListPage.jsx
src/routes/__tests__/TaskDetailsPage.test.jsx
src/routes/index.jsx

This PR changes the id in the task detail url to reflect the process instance id and not the task id anymore. Subsequently, API calls to camunda have changed to support this change. As well this, the PR also includes work for COP-6536 whereby doing this work in isolation would introduce breaking changes
- Scenario 1: Task owner views task details page
-- GIVEN I have claimed a task that is "in progress"
-- WHEN I view the task details page
-- THEN I have an option to 'Un-claim" the task
- Scenario 2: View an un-claimed task details page
-- GIVEN an "Outstanding" task is NOT claimed
-- WHEN I view the task details page
-- THEN I have an option to 'Claim" the task
- Scenario 3: Non-owner views a claimed task details page
-- GIVEN a task is claimed by another targeter …

COP-6567 Display task details page based on process instance not task id

---

src/routes/TaskDetails/TaskDetailsPage.jsx
src/routes/__tests__/TaskDetailsPage.test.jsx

This PR only renders the form buttons when the user task associated with the process instance has a type of `developTarget`
- Claim a target from task list page
- *You should see the form buttons*
- Unclaim the task
- *You should NOT see the form buttons*
\* Required

COP-6534 Hide form button when no users tasks are available, only show form buttons when user task type is equal to "developTarget"

---

cypress/integration/cerberus/task-details.spec.js
cypress/integration/cerberus/task-management.spec.js
cypress/support/commands.js

Tests added to check user journey of Dismiss a task
Updated tests to check mandatory error when reason not selected while assessment complete
Check if a task moved into "In progress tab"  after claiming it.
Update tests to adapt latest changes. Following tickets automation covered in this PR, since changes are dependant.
COP-5502
COP-6431
COP-5506
npm run cypress:test:local
\* Required

COP-5502: Add test for Dismiss a task & Claimed task moved to In progress tab

---

cypress/integration/cerberus/task-details.spec.js
cypress/integration/cerberus/task-management.spec.js

Test added to cover the following scenarios,
Scenario: Task owner views task details page
GIVEN I have claimed a task that is "in progress"
WHEN I view the task details page
THEN I have an option to 'Un-claim" the task
Scenario: View an un-claimed task details page
GIVEN an "Outstanding" task is NOT claimed
WHEN I view the task details page
THEN I have an option to 'Claim" the task
Scenario: Non-owner views a claimed task details page
GIVEN a task is claimed by another targeter
WHEN I view the task details page
THEN there is no option to "Claim" OR "Un-claim" the task
execute all tests in task-details.spec.js 
\* Required

COP-6536: Add test to hide claim & unclaim button on task details page

---

package-lock.json
package.json

Bump formio-gds-template version, remove --watch as no longer supported/required
- delete node modules
- delete package lock
- run npm i
- open Cerberus UI
- pages and forms should retain their styling
\* Required

COP-4073 Bump formio-gds-template version

---

cypress/integration/cerberus/issue-a-target.spec.js
cypress/integration/cerberus/task-details.spec.js
cypress/support/commands.js

Tests added for the following scenario,
Scenario: Task owner views task "In-progress"
GIVEN I am a task owner AND the task is "In-progress"
WHEN I view the task details
THEN there are options to Issue target/Complete/Dismiss
Scenario: Task owner views a "Target Issued" task
GIVEN I am a task owner AND the task is "Target Issued"
WHEN I view the task details
THEN there are NO options to Issue target/Complete/Dismiss
(NOTE: We may want to re-visit this acceptance criteria to allow users to complete or dismiss issued targets, but there are bigger implications)
Scenario: Task owner views "Complete" task
GIVEN I am a task owner AND the task is "Complete"
WHEN I view the task details
THEN there are NO options to Issue target/Complete/Dismiss
Scenario: Non-Task owner views task
GIVEN I am NOT a …

COP-6534: Add tests for Hide / Show action buttons

---

src/components/ClaimTaskButton.jsx
src/components/__tests__/ClaimTaskButton.test.jsx
src/constants.js
src/govuk/Tabs.jsx
src/routes/TaskLists/TaskListPage.jsx

When user clicks unclaim from the in progress tab, and the page they are on is greater than the total number of pages for the new it shows no new tasks.
Updated tab loading to enable forcing the new tab to display
Updated the unclaim button to trigger the force new tab
- claim a task from new tab
- find it on in progress tab
- unclaim it
- > you should be taken to the new tab, at the top
- find a task towards the end of the in progress pages
- unclaim it
- > you should be taken to the new tab, at the top
\* Required

COP-6761 Pagination on unclaim click

---

cypress/integration/cerberus/task-details.spec.js
cypress/integration/cerberus/task-management.spec.js
cypress/support/commands.js

This PR has test for verifying user comments in the activity history. Improved the logic to find a task in the pagination.
OR
select task-details.spec.js and run
\* Required

COP-5769: Add test for View user activity about a targeting task (comments) in the task history

---

cypress/integration/cerberus/task-details.spec.js
cypress/support/commands.js

This has tests for the following scenarios,
**Scenario 1:**
- claim a task from new tab
- find it on in progress tab
- unclaim it
- you should be taken to the new tab, at the top
**Scenario 2:**
- find a task towards the end of the in progress pages
- unclaim it
- you should be taken to the new tab, at the top
execute task-details.spec.js
\* Required

COP-6761: Add tests for Unclaim a task Successfully from In Progress tab & verify it moved to New tab

---

src/routes/TaskLists/TaskListPage.jsx

Currently, cerberus sorts the targets by page correctly. However the 10 targets that appear in the list are not guaranteed to be sorted themselves. This PR solves this issue
- Pull and run cerberus natively
- Submit targets to cerberus with varying scheduled arrival times (note the business key and the associated arrival time)
- *The targets you submitted should appear in the correct order in the list (earlier arrival first)*
\* Required

COP-6009 Sort targets on single page in task list

---

src/components/RenderForm.jsx
src/routes/__tests__/TaskDetailsPage.test.jsx

When the form service returns an error code, this PR handles the error gracefully. Before, the `form` state was set to null after an error code was returned from the form service however, this has now been removed thus the `form` state remains an empty object. As a result the subsequent form.io methods a now being called against an empty object and not `null`
- Claim a target from the target list
- *Task details page should render without error*
- Cause an error to be returned from the form service (via secrets or by changing the form name used to query the form service)
- Navigate to the same target claimed
- *The task details page should not break*
- *An error code should be returned matching the method used to cause the error i.e. form name change equalling a …

COP-7114 Handle form service errors gracefully

---

cypress/integration/cerberus/issue-a-target.spec.js
cypress/integration/cerberus/task-details.spec.js
cypress/support/commands.js

Tests updated to cover all the following scenarios,
open a task from the `Issued` tab
> you should have no `claim` or `unclaim` button
> you should not see an `assigned to` message
> you should not have the action buttons (Issue target, Assessment complete, Dismiss)
> you should not have a notes form
open a task from the 'Completed` tab
> you should have no `claim` or `unclaim` button
> you should not see an `assigned to` message
> you should not have the action buttons (Issue target, Assessment complete, Dismiss)
> you should not have a notes form
open a task from the `in progress` tab that is not assigned to you
> you should have no `claim` or `unclaim` button
> you should see the text 'Assigned to <user>'
> you should not have the action buttons (Issue target, Assessment complete, …

COP-6747: Update tests for Refactor target status for cerberus

---

src/routes/TaskLists/TaskListPage.jsx

When the due date for a target is null, it is placed lower in the target list than a due date that is truthy.
- Navigate to target list
- Move through pages until you find a page containing both null arrival dates and valid arrival dates (null dates expressed as `Unknown` in the target list)
- *You should see the unknown arrival dates appear below the valid arrival dates*
\* Required
- [] Does it have tests?

COP-6009 Null due dates sort to bottom of target list

---

src/routes/TaskDetails/TaskVersions.jsx

The task version list was rendering in the wrong order. This is due to the latest task version being the last element in the array. To fix this, reversing the array is the fix
- Check a target with multiple versions
- *It should render correctly*
\* Required

COP-6820 Reverse task version list

---

cypress/integration/cerberus/formapi-404.spec.js
scripts/env-setup-dev.sh
scripts/env-setup-sit.sh

This PR has test to verify Cerberus-UI doesn't break when form api returns 404.
Form API mocked with Cypress route to return 404 before hitting the form API service.
select formapi-404.spec.js and run
\* Required

COP-7114: Add test to verify Cerberus-UI doesn't break when form api returns 404

---

cypress/fixtures/tasks-org-null.json
cypress/integration/cerberus/create-tasks.spec.js

create a task with payload contains organisation as null and it should be rendered without an issue on UI.
All the tests to create tasks with RoRo-Tourist skipped since it has problem and failing on Camunda.
run create-tasks.spec.js 
\* Required

COP-6868: Add test to create a task with payload contains organisation as null

---

cypress/integration/cerberus/issue-a-target.spec.js
cypress/integration/cerberus/task-details.spec.js
cypress/support/commands.js

Assessment complete and dismiss a task tests are updated to match with the latest changes.
Fix added for the Flaky tests to find a task in the respective tabs. 
execute tests from spec, task-details.spec.js 
\* Required

COP-6420: Update tests for complete assessment where options changed from checkboxes to radio buttons

---

src/components/RenderForm.jsx
src/utils/__tests__/findAndFormat.test.js
src/utils/findAndFormat.js

The date of birth and document expiry fields do not prefill correctly on the target information sheet. This is due to the provided date being in ISO format (excluding time) which formbuilder is not able to pre-populate the fields with. Formbuilder accepts the date as `DD/MM/YYYY` whereas it was receiving `YYYY-MM-DD`. This code just formats the dob and docExpiry to match the date format expected by formbuilder.
- Go to cerberus dev and submit a target information sheet via a task (have dev tools open and check the req payload's dob and docExpiry fields)
- Select task from task list and click `Issue a Target`
- Navigate to the dob and doc expiry fields
- *The fields should be populated correctly*
- Submit the form
- *The req payload dob and docExpiry should have the …

COP-7375 RoRo-accompanied task driver details DOB and travel doc expiry date not populated correctly

---

cypress/integration/cerberus/issue-a-target.spec.js
cypress/integration/cerberus/task-details.spec.js

Test to check matching selectors displayed on task details page (COP-5824)
Test updated to choose target indicators and target hub from ref-data list 
execute tests from issue-a-target.spec.js & task-details.spec.js 
\* Required

COP-7315: Update tests to choose target indicators and target hub from ref-data list & check matching selectors

---

src/components/RenderForm.jsx
src/utils/__tests__/findAndFormat.test.js

This PR add formatting for the `threatIndicators` property on the `targetInformationSheet` sent from camunda. Due to time constraints, the formatting has been done here until a fix is implemented in the relevant workflow.
- Submit new target and navigate to target in UI
- Issue a target selecting several threat indicators
- Submit and assign task raised in v2 to yourself
- Navigate to COP UI v2 and find task assigned to yourself
- *You SHOULD see the threat indicators selected in the target task form summary*
\* Required

COP-7460 targetTask threat indicators not appearing in summary

---

src/components/RenderForm.jsx
src/utils/__tests__/findAndFormat.test.js

This PR handles when the target info sheet values are null (in particular for when the threat indicator is an empty string in an array)
- Submit target with threatType equal to empty string (escaped)
- claim target created
- Open issue a target
- *The threat indicator dropdown should not be populated with anything*
\* Required

COP-7460 Handle null target info values

---

.eslintrc.js
cypress/integration/cerberus/create-tasks.spec.js
cypress/integration/cerberus/issue-a-target.spec.js
cypress/integration/cerberus/task-details.spec.js
cypress/integration/cerberus/task-management.spec.js
cypress/support/commands.js

Once the data cleared out on Dev / Local environment, some of the tests failed because it look for an element from Pagination.
Test adapted to work even when there is a single page in each of the tab.
Enable RoRo tourist task creation tasks.
open the report mochawesome-report/mochawesome.html and check status of all tests.
\* Required

Fix broken test due to pagination and enable RoRo tourist task creation tests

---

.drone.yml
README.md
cypress/config/sit.json
cypress/integration/cerberus/formapi-404.spec.js
cypress/integration/cerberus/issue-a-target.spec.js
cypress/integration/cerberus/task-details.spec.js
cypress/integration/cerberus/task-management.spec.js
cypress/support/commands.js
cypress_runner.js
get_secrets.js
kube/job.yml
kube/secret.yml
package.json
scripts/run-tests.sh

CronJob added on kubernetes to run automation tests every 2 hour between 8am to 6pm. Results would be slacked to `cop-tests-report` channel.
Tests updated such that it would make sure there is a task before claiming / un-claiming a task. 
ssh to `kubectl --context=acp-notprod_COP --namespace=cop-cerberus-sit`
run the following command
kubectl --context=acp-notprod_COP --namespace=cop-cerberus-sit get cronjobs
you should see the following job
`cerberus-functional-tests-sit`
\* Required

COP-7185: Setup CronJob to run Automation tests against SIT environment

---

.drone.yml
README.md
cypress.json
cypress/config/dev.json
cypress/config/sit.json
cypress/config/staging.json
cypress/integration/cerberus/create-tasks.spec.js
cypress/integration/cerberus/formapi-404.spec.js
cypress/integration/cerberus/issue-a-target.spec.js
cypress/integration/cerberus/login.spec.js
cypress/integration/cerberus/task-details.spec.js
cypress/integration/cerberus/task-management.spec.js
cypress_runner.js
get_secrets.js
package.json

Setup CronJob to run Automation functional tests on Staging environment once in a day. 
Results would be slacked to `cop-tests-report` channel.
Tests updated with `after` step to log out  after every spec completed.
It needs access to cop-cerberus-staging namespace
ssh to kubectl --context=acp-prod_COP --namespace=cop-cerberus-staging
run the following command
kubectl --context=acp-prod_COP --namespace=cop-cerberus-staging get cronjobs
you should see the following job
cerberus-functional-tests-staging
\* Required

COP-7632: Setup cronJob to run automation tests on Staging environment

---

src/routes/TaskDetails/TaskVersions.jsx

The data structure for Passengers has been updated and now requires us to map out the childSets.
This code handles it for passengers, and also for matched selectors as it uses the same structure.
**scenario 1**
- create an unaccompanied target
- view target in cerberus UI
- task details section should populate data as normal
**scenario 2**
- create an accompanied target with 0 passenger
- view target in cerberus UI
- task details section should populate data as normal, with a driver section and no passenger details
**scenario 3**
- create an accompanied target with 2 passengers
- view target in cerberus UI
- task details section should populate data as normal, with a driver section and a passenger section with two passengers populated
\* Required

COP-7676 Display passengers

---

README.md
cypress/integration/cerberus/create-tasks.spec.js
cypress/integration/cerberus/formapi-404.spec.js
cypress/integration/cerberus/issue-a-target.spec.js
cypress/integration/cerberus/task-details.spec.js
cypress/integration/cerberus/task-management.spec.js
cypress/support/commands.js

Tests are updated to use the URL with businessKey to navigate to taskDetailsPage.
README updated with correct context name for staging. 
Please refer the README for the context, namespace and secretName for different env
./scripts/env-setup.sh {context} {namespace} {secretName}
update cypress.env.json with respective url for
"cerberusServiceUrl": "xxx",
"formApiUrl": "xxx",
check the report mochawesome-report/mochawesome.html for status. 
\* Required

COP-5748: Update tests to URL with businessKey instead processInstanceId

---

src/routes/TaskDetails/TaskSummary.jsx

Excess letters were in the field, removed them
Open a task with a trailer, there should be no excess letters
\* Required

COP-7052 Remove unneeded text

---

src/routes/TaskDetails/TaskDetailsPage.jsx
src/routes/TaskLists/TaskListPage.jsx
src/routes/__tests__/TaskListPage.test.jsx

The business key contains forward slashes causing the single target page to not render anything. This PR encodes the business key to UTF-8 by replacing forward slashes with `%2F` allowing the user to use the business key (escaped) in the url. As well as this, by using encodeURIComponent (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) it escapes the whole business key
- Post a target with a business and movement id containing forward slashes
- Search task list for target
- *The target should have an escaped business key rendered*
- Click on target
- *It should render as normal*
\* Required

Escape business key in the URL

---

cypress/integration/cerberus/task-version-details.spec.js
cypress/support/commands.js

Use same BusinessKey for all the payloads when sending different movements.
Please refer the README for the context, namespace and secretName for different env
./scripts/env-setup.sh {context} {namespace} {secretName}
update cypress.env.json with respective url for
"cerberusServiceUrl": "xxx",
"formApiUrl": "xxx",
execute spec task-version-details.spec.js 
\* Required

COP-7949: Update test to have same businessKey when different payloads sent

---

src/routes/TaskDetails/TaskVersions.jsx

The date under the version title on the /tasks/id page was always showing as `invalid date`, the position of the `.format()` was incorrect and causing this
- Open a Cerberus task
- Under the version number you should see a date format of `DD MMM YYYY at HH:mm`
\* Required

COP-7637 Update date formatting position so it formats date correctly

---

src/components/Header.jsx
src/components/__tests__/Header.test.jsx
src/routes/TaskDetails/TaskVersions.jsx

Remove `Issue a Target` option from nav bar as users cannot create a new target using that form
- open Cerberus-COP
- you should not see `Issue a Target` as a nav bar option
\* Required

COP-6817 Remove Issue a Target from navbar

---

src/routes/TaskDetails/TaskVersions.jsx

The date under the version title on the /tasks/id page was always showing as `invalid date`, the position of the `.format()` was incorrect and causing this
- Open a Cerberus task
- Under the version number you should see a date format of `DD MMM YYYY at HH:mm`
\* Required

Update date formatting

---

README.md
cypress/integration/cerberus/create-tasks.spec.js
cypress/integration/cerberus/formapi-404.spec.js
cypress/integration/cerberus/issue-a-target.spec.js
cypress/integration/cerberus/task-details.spec.js
cypress/integration/cerberus/task-management.spec.js
cypress/integration/cerberus/task-version-details.spec.js
cypress/support/commands.js
get_secrets.js
scripts/env-setup.sh

Delete all the automation test data one day older and keep the latest test data.
Simplify environment setup to run the tests against different env from local machine.  
./script/env-setup.sh dev
\* Required

Delete only one day older tasks & improve environment setup

---

src/routes/TaskLists/TaskListPage.jsx

Signed-off-by: Andrew Scrivener <andrew.scrivener@digital.homeoffice.gov.uk>
https://support.cop.homeoffice.gov.uk/browse/COP-6072
The business have requested that we display 100 tasks per page rather than 10 and pagination be shown thereafter.   
Does pagination display when more than 100 tasks are available for the task list page.
\* Required

ItemsPerPage increased from 10 to 100

---

cypress/fixtures/RoRo-Unaccompanied-RBT-SBT.json
cypress/fixtures/unaccompanied-task-details.json
cypress/integration/cerberus/task-management.spec.js
cypress/integration/cerberus/task-version-details.spec.js

Test added to create a task with selector matches in the payload and verify it on the UI.
Updated arrival date time sorting order failing tests.
run tests `Should verify task version details of unaccompanied task on task details page` from task-version-details.spec.js
\* Required

COP-7942: Add test to verify selector matches displayed as is from payload

---

.eslintrc.js
cypress/fixtures/RoRo-Accompanied-Freight.json
cypress/fixtures/RoRo-Unaccompanied-RBT-SBT.json
cypress/fixtures/RoRo-task-v1-target-update.json
cypress/fixtures/RoRo-task-v3-target-update.json
cypress/fixtures/accompanied-task-details.json
cypress/fixtures/unaccompanied-task-details.json
cypress/integration/cerberus/task-version-details.spec.js

Tests added to verify the following scenarios,
Scenario 1: View target details (Version 1)
GIVEN I have received one or more targeting indicators in ANY movement node of the data payload for a task
WHEN I view the task details
THEN I can see a list of Targeting indicators as per the attached screen shot as the first item in the task details section
Scenario 2: Update current version
GIVEN A task already exists
WHEN Targeting Indicators are received in a subsequent payload without an attribute change
THEN the Targeting Indicators are added to the current version
Scenario 3: Additional Version
GIVEN A task already exists
WHEN Targeting Indicators are received in a subsequent payload with an attribute change
THEN only the Targeting Indicators included in the payload are displayed in the new …

COP-6905: Add tests to check Target Indicators

---

jest.setup.jsx
src/components/Header.jsx
src/components/__tests__/Header.test.jsx
src/routes/TaskDetails/TaskDetailsPage.jsx
src/routes/TaskDetails/TaskVersions.jsx

AC: latest version of target should be expanded by default
Notes:
- GDS accordion stores last selected state of accordion (open/closed) and persists
Updated:
- gave every accordion item a unique ID connected to it's task ID so when state is saved to session storage by the accordion it doesn't impact other targets accordions
- set latest version to be open by default
- updated sign out to include clearing session and local storage data
- click on a target (remember this target url)
- > the latest version should be open
- close the latest version
- refresh the page
- > latest version should stay closed
- go back to target list
- click on a different target
- > latest version should be open
- go to your first target again
- > latest version should be closed (as you left it in a closed state …

COP-6433 auto open accordion

---

cypress/integration/cerberus/task-version-details.spec.js
cypress/support/commands.js

Add tests to verify the following scenario,
- click on a target (remember this target url)
- the latest version should be open ​
- close the latest version
- refresh the page
- latest version should stay closed
​
- go back to target list
- click on a different target
- latest version should be open
- go to your first target again
- latest version should be closed (as you left it in a closed state earlier
log out
log in
go to your first target again
latest version should be open (as logging out clears all your states)
run all the tests from test spec,  `task-version-details.spec.js`
\* Required

COP-6433: Add test to verify Auto-expand current task version

---

.eslintrc.js
jest.setup.jsx
src/__mocks__/keycloakMock.js
src/__mocks__/keycloakNonTargeterMock.js
src/components/__tests__/ClaimTaskButton.test.jsx
src/components/__tests__/Header.test.jsx
src/constants.js
src/routes/TaskLists/TaskListPage.jsx
src/routes/__tests__/TaskDetailsPage.test.jsx
src/routes/__tests__/TaskListPage.test.jsx
src/routes/__tests__/TaskListPageNonTargeter.test.jsx

Only users with the group `bf-intel-targeters` should be able to see tasks in the task lists
GIVEN I am a COP user
WHEN I included in the "bf-intel-targeters" group
THEN I am able to view the Targeters task list
GIVEN I am a COP user
WHEN I am NOT included in the "bf-intel-targeters" group
THEN I am NOT able to view the Targeters task list
**To test as a dev:**
- in `constants.js` file, set `TARGETER_GROUP` to `bf-intel-targeters`
- (check if devops have given you that group yet)
- > if you have that group, go to `/tasks` and you should see tasks
- > if you do not have that group, go to `/tasks` and you should NOT see tasks
**If you have bf-intel-targeters group**
- in `constants.js` file, set `TARGETER_GROUP` to `not-my-group`
- > go to `/tasks` you should NOT see tasks
**If you do not …

COP-8861 Restrict target task view to user with target group

---

src/components/ClaimTaskButton.jsx
src/components/__tests__/ClaimTaskButton.test.jsx
src/routes/TaskDetails/TaskDetailsPage.jsx
src/routes/TaskLists/TaskListPage.jsx
src/routes/__tests__/TaskListPage.test.jsx

Display claimed by name on task list
- Added a check on the ClaimTaskButton component for when assignee !== currentUser, to now return Assigned to username.
- Included IN_PROGRESS tab to show all claim button types
- Added comment to TaskDetails page to explain why only two scenarios covered in that code now
- Updated tests
- go to In progress tab
- > you should see `assigned to <email>` if someone else has claimed the task
- > you should see `unclaim` if you have claimed the task
- go to task details
- > you should see `assigned to <email>` if someone else has claimed the task
- > you should see `assigned to you unclaim` if you have claimed the task
- > you should see `claim` if no one has claimed the task
\* Required

Cop 8798 display claim name

---

cypress/fixtures/RoRo-task-v2.json
cypress/integration/cerberus/task-version-details.spec.js
cypress/support/commands.js

Tests added to verify to check number of difference between versions & highlighted differences displayed on task details page.
execute test `Should verify difference between versions displayed on task details page` from spec `task-version-details.spec.js`
\* Required

COP-8704: Add tests to check difference between versions displayed on task details page

---

src/routes/TaskLists/TaskListPage.jsx
src/routes/__tests__/TaskListPage.test.jsx

Design change to move the count to be shown in brackets after the label in the tab
Tabs should read
`New (123)` not `123 New`
\* Required

COP-9152 Move count shown in tabs to after label

---

src/routes/TaskLists/TaskListPage.jsx
src/utils/__tests__/calculateDatetimeDifference.test.js
src/utils/calculateDatetimeDifference.js

This PR adds an aditional field to the TaskListPage which contains the relative time difference between the departure time and booking time.
In addition, also addresses a minor issue where by the variable containing the merged departure time and booking time is used to display the booking time.

calculate relative time difference between the booking date and departure date

---

src/config.js
src/routes/TaskDetails/TaskSummary.jsx
src/routes/TaskDetails/TaskVersions.jsx
src/routes/TaskLists/TaskListPage.jsx
src/utils/__tests__/calculateDatetimeDifference.test.js
src/utils/__tests__/formatField.test.jsx
src/utils/calculateDatetimeDifference.js
src/utils/formatField.jsx

This PR formats the new type given to the booking date time. The booking datetime now consists of 2 parts, the `bookingDatetime` (BDT) and the `scheduledDepartureTime` (SDT) which is required for the task versions section.  
- Navigate to a single task (do this for when there is a BDT present - and when there isn't)
- *The task version summary BDT should be displayed correctly*
- Open the task version and navigate to the BDT
- *It should be displayed correctly according to what information was provided i.e. with both BDT and  SDT it renders `2 Aug 2020 at 09:15, a day before travel` and for only BDT `2 Aug 2020 at 09:15`*
\* Required

COP-9050 Difference between the date of departure and the booking date

---

src/routes/TaskLists/TaskListPage.jsx

This PR fixes a minor bug where relative time calculation would appear on the same line as the booking time when viewed on a wide display.
- On the task list, if scheduled departure time is available, the relative time difference calculation e.g. `Booked 2 days before travel` should appear below the line containing the booking date.
\* Required

fixed minor bug as part of COP-9192 where relative time calculation would appear on the same line as the booking time 

---

src/routes/TaskLists/TaskListPage.jsx

- refreshing page was sometimes resulting in the original count of tasks being displayed
- > added conditionals to when we run task counts to avoid running before filters applied
- selecting and deselecting both was sometimes resulting in a dangling comma in the filter array (`,word` or `word,,word`) which caused the get call to 404
- > updated how we handle 'both' which requires no code in the filter array to prevent chance of comma
- select a mode
- select both & apply
- select yes & apply
- select both & apply
- select no & apply
- refresh the page 9ish time
none of the above should result in an inconsistent count or 404
\* Required

COP-9191 Filters bug fixes

---

src/routes/TaskLists/TaskListPage.jsx

In fixing another bug, introduced a bug where get task count no longer ran when filters were reset.
Added a state to indicate when filters were being reset to prompt the get task count to run
- apply filters
- clear filters
- task counts should update
\* Required

COP-9191 Get updated count when handleResetFilters triggered

---

src/routes/TaskLists/TaskListPage.jsx

Selecting 'both' after some combinations of check/uncheck resulted in the get counts call not running
Updated the switch to trigger getting a new set of counts to handle all scenarios
- select has selectors and apply
- select has no selectors and apply
- select both and apply
Counts should update on each apply
\* Required

COP-9191 - Extend getTaskCount switch to include on load scenarios

---

cypress/fixtures/taskInfo-known/RoRo-Acc-TaskDetails-expected.json
cypress/fixtures/taskInfo-unknown/RoRo-Acc-VehOnly-expected.json
cypress/fixtures/taskInfo-unknown/RoRo-Acc-VehWithTrail-expected.json
cypress/integration/cerberus/task-details.spec.js
cypress/support/commands.js

Add tests to check the Booking date & time and Departure time difference on TaskList page and task summary.
run following tests from spec `task-details.spec.js` 
`Vehicle and Trailer - Unknown values in Task List & Task Summary`
`Should display correct values for PERFDRIVER Driver, Booking, Vehicle, tasklist, task summary`
`Should display correct values for PERFDRIVER Driver, Booking, Vehicle, tasklist, task summary`
\* Required

COP-9192: Add tests to verify Booking Date time on taskList Page and taskSummary

---

cypress/integration/cerberus/filter-tasks-by-pre-arrival-mode.spec.js
cypress/integration/cerberus/filter-tasks-by-selectors.spec.js
cypress/integration/cerberus/task-management.spec.js
cypress/support/commands.js

Add tests to check the filter functionality using selectors.  Tests cover the following scenarios,
Scenario: Filter task list with selector
GIVEN a targeter has tasks in the task list (New, In progress, Complete...)
WHEN they select the "Has Selector" radio filter and click "Apply"
THEN only tasks with at least one selector match in the current version are displayed
Scenario: Filter task list with no selectors
GIVEN a targeter has tasks in the task list (New, In progress, Complete...)
WHEN they select the "Has no Selector" radio filter and click "Apply"
THEN only tasks with NO selector matches in the current version are displayed
Scenario: Filter task list with/ without selectors
GIVEN a targeter has tasks in the task list (New, In progress, Complete...)
WHEN they select the "Both" radio …

COP-9191: Add tests to check selectors filter functionality

---

src/routes/TaskLists/TaskListPage.jsx

This PR fixes a layout bug where target indicator & risk score would appear on the same line.
On the tasks list page, the Risk Score should appear above the targeting indicators.

fixed layout bug where target indicator & risk score were on the same line

---

cypress/fixtures/RoRo-task-v1.json
cypress/fixtures/RoRo-task-v3.json
cypress/fixtures/task-version-differences.json
cypress/integration/cerberus/task-version-details.spec.js
cypress/support/commands.js

Automation tests updated to check the difference between the versions when the value of the field is empty.
execute the test, `Should verify difference between versions displayed on task details page` from spec `task-version-details.spec.js`
\* Required

COP-9273: Update tests to check the differences in versions when the value is empty

---

cypress/fixtures/RoRo-task-v1-target-update.json
cypress/fixtures/RoRo-task-v3-target-update.json
cypress/integration/cerberus/task-risk-score-verify.spec.js
cypress/support/commands.js

Add tests to verify the following scenarios
1.) Multiple Tasks with 1 TI displays correct score for the TI
2.) Task with 16 TIs displays the correct aggregated score
3.) Task with multiple versions - The aggregated score is for the TIs in the latest version and does NOT include the score for TIs in previous 2 versions
4.) Tasks without TIs present are not displaying a score/value
run all the tests from spec `task-risk-score-verify.spec.js`
\* Required

COP-9051: Add tests to verify Risk score on task list page

---

src/routes/TaskDetails/TaskVersions.jsx
src/routes/TaskLists/TaskListPage.jsx

This PR solves 2 minor cosmetic problems (COP-8934).
1) On task details page, if there are no passangers for a task, the passengar details field would show **unknown**, this now says **None**
2) When vieing a task in detail, if there were no passenger(s), the passenger(s) section would still be rendered with empty fields, this now renderes i fthere are passengers and doesn't when there no passengers.
- On the task list, when there are no passengers, under **Passenger detials** header, it should say **None** .
- When viewing a task in detail (click on a task), select a task with no passenger(s), when viewing the version section, the passenger section will not be rendered. 
- Repeating the steps mentioned above for a task with passengers will result in the the …

cop-8934 - no passenger details

---

src/routes/TaskLists/TaskListPage.jsx
src/routes/__fixtures__/variableInstanceTaskSummaryBasedOnTIS.fixture.json
src/routes/__tests__/TaskListPage.test.jsx

This PR removes the encoding on the business key that we placed on the Cerberus business key as we now replace the forward slash with underscores. This should no longer cause issues re s3 bucket storage
- Claim task and run through to the end of it's process
- *The correct info should be stored in s3 and the process moved along as normal*
\* Required

COP-9403 Remove business key encoding

---

src/routes/TaskLists/TaskListPage.jsx

This PR fixes a bug where the when there were no risk scores, it would return **Risk Score: ** instead of **Risk Score: 0**
- On the tasts list, each task will have a Risk score: along with a value if risk scores are present e.g. **Risk Score: 25** and just **Risk Score: 0** if there's no risk score to calculate.
\* Required

Risk score 0 when none is avaiable

---

src/routes/TaskLists/TaskListPage.jsx
src/routes/__tests__/TaskListPageFilters.test.jsx

This PR is a minor cosmetic changing of the selector filter names.
JIRA Ticket: [https://support.cop.homeoffice.gov.uk/browse/COP-9511](url)
- On the task list, locate the filter section, specifically the selectors radio button group.
- It should now say: 
> **Not present** 
> **Present**
> **Any** 
instead of 
> **Has no selector**
> **Has selector**
> **Both**
\* Required

COP-9511 Change wording of selector filter

---

src/routes/TaskDetails/TaskVersions.jsx
src/routes/TaskLists/TaskListPage.jsx
src/routes/__assets__/TaskDetailsPage.scss
src/routes/__fixtures__/variableInstanceStatusIssued.fixture.json
src/routes/__tests__/TaskDetailsPage.test.jsx
src/utils/rickScoreCalculator.jsx

This PR restructures the Targeting Indicators layout in task details.
JIRA Ticker: https://support.cop.homeoffice.gov.uk/browse/COP-9286
- Confirm that new layout against old layout
> **New layout**
vs.
> **Old layout**
> Due to the tight coupling of the task details page layout, The new layout will nto exactly match that of the prototype suplied in the Jira ticket [https://support.cop.homeoffice.gov.uk/browse/COP-9286](url).
\* Required

COP-9286 UX to display total risk score in task details

---

src/routes/TaskDetails/TaskVersions.jsx

COP-9402: Rule matches are now shown as per new designs
1. Select a task with rules in any tab state(New, In progress, Issued, Complete) on Task management landing page.
2. The journey would take the user to the Task details page for the selected task
3. Go to the Rules matched section
4. The new Rules matched section is shown as per new design
\* Required

COP-9402: rules matches are now shown as per new design

---

src/routes/TaskLists/TaskListPage.jsx
src/routes/__tests__/TaskListPage.test.jsx
src/routes/__tests__/TaskListPageFilters.test.jsx

This PR is based off the cop-9367-api-changes-v1 branch
- adds filter functionality back in
- changes modes to checkboxes
- does NOT persist filters on page refresh (that will come in a future PR)
_Run with cop-9367-api-changes-v1_
- select filters : they should be checked
- clear filters : they should all become unchecked
- select filters : they should be checked
- apply filters : task list and counts should update and return tasks that match the filters
- select different filters
- apply filters : task list and counts should update and return tasks that match the new filters
- clear filters: task list and counts should update and return ALL tasks, filters should be unchecked
\* Required

COP-9367 Handle filters

---

kube/deployment.yml

We hit 2 different APIs from the UI now
- `/camunda/engine-rest`
- `/camunda/v1`
Previously everything was configured with the assumption `camunda\engine-rest` was the only one and we have discovered we now need to update the API path here to include engine-rest so it hits the correct endpoint that it's checking.
\* Required

COP-9662 Update API path for live probe in deployment.yml

---

src/routes/TaskLists/TaskListPage.jsx
src/routes/__tests__/TaskListPageFilters.test.jsx

AC: persist filter selections on page refresh
Store selections in localstorage
Load filters localstorage, set checked state, get counts & tasks on page load
- select some filters & apple
- refresh page : filters should remain selected and counts/tasks should be for those filters
- clear filters
- refresh page : page should load with no filters
\* Required

COP-9661 Add functions to persist filters on page refresh

---

cypress/fixtures/accompanied-task-2-passengers-details.json
cypress/fixtures/task-details-versions.json
cypress/fixtures/unaccompanied-task-details.json
cypress/integration/cerberus/create-tasks.spec.js
cypress/integration/cerberus/task-version-details.spec.js
cypress/support/commands.js

Update automation tests to verify the Rules matches with the latest changes on UI. Following scenarios are covered,
Scenario 1: 1 Matched rule
GIVEN a task has a matched rules
WHEN I view the task details
THEN the matched rule is displayed as the prototype
Scenario 2: More than 1 Matched rule
GIVEN a task has multiple matched rules
WHEN I view the task details
THEN the first rule is displayed as Rule Matched and any other rules are displayed in "Other rule matches" as the prototype
run all the tests from spec `task-version-details.spec.js`
run test `Should create a task with a payload contains RoRo Tourist and check AbuseType set to correct value` from spec `create-tasks.spec.js`.
\* Required

COP-9402: Update tests to verify the Rules matches with the latest changes on UI

---

cypress/integration/cerberus/task-details.spec.js
cypress/support/commands.js

Update Automation tests to check the Assessment Complete and Dismissed outcome and notes in the activity log. 
Following scenarios are covered in the tests,
GIVEN a task is dismissed
WHEN the reason and notes are submitted
THEN "Task dismissed", the reason and notes are displayed in the activity log
Scenario: Assessment complete
GIVEN a task assessment is complete
WHEN the reason and notes are submitted
THEN "Assessment complete", the reason and notes are displayed in the activity log
run the following tests from spec `task-details.spec.js`
`Should complete assessment of a task with a reason as take no further action`
`Should dismiss a task with a reason`
\* Required

COP-9556: Update test to check the Assessment Complete and Dismissed outcome and notes in the activity log

---

cypress/fixtures/accompanied-task-2-passengers-details.json
cypress/fixtures/accompanied-task-details.json
cypress/fixtures/task-details-versions.json
cypress/fixtures/task-version-differences.json
cypress/fixtures/tourist-task-details.json
cypress/integration/cerberus/filter-tasks-by-pre-arrival-mode.spec.js
cypress/integration/cerberus/filter-tasks-by-selectors.spec.js
cypress/integration/cerberus/formapi-404.spec.js
cypress/integration/cerberus/issue-a-target.spec.js
cypress/integration/cerberus/task-details.spec.js
cypress/integration/cerberus/task-management.spec.js
cypress/integration/cerberus/task-risk-score-verify.spec.js
cypress/integration/cerberus/task-version-details.spec.js
cypress/support/commands.js

Update automation tests to inline with latest API and UI changes
note: some of the tests still failing due to `selector` section not available on task details page
\* Required

COP-9550: Update automation tests to inline with latest API and UI changes

---

cypress/integration/cerberus/filter-tasks-by-pre-arrival-mode.spec.js
cypress/integration/cerberus/task-details.spec.js
cypress/support/commands.js

Add / update tests to verify the following scenarios,
As well as testing the AC of this ticket
please check these as they have been updated with the new API
Counts
go to /tasks
task counts in tabs should reflect the number of tasks for the status
pagination should work 
Filters
click on some filters : they should be selected but not applied
click reset : filters should become unselected
click on some filters
click apply : tasks and counts should update based on the filters
click on some other filters
click apply : tasks and counts should update based on the filters
click reset : filters should become unselected, tasks and counts should update to 'all'
run all the tests from spec `filter-tasks-by-pre-arrival-mode.spec.js`
\* Required

COP-9210: Add Pre arrival modes filter tests to adapt checkboxes

---

src/routes/__assets__/TaskDetailsPage.scss

This PR fixes a bug where the spacing between columns in task details would almost allow neighboring columns to meet.
**JIRA Ticket**: https://support.cop.homeoffice.gov.uk/browse/COP-9720
- In a separate browser tab, load up Cerserus-Service (dev env).
- Locate the task titled **CHARLES-2022-01-05-4** or **CHARLES-2022-01-05-3** or **CHARLES-2022-01-05-2** and click on view details.
- Compare the **Booking and check-in** columns (See attached screenshots for guidance).
> **Bug**
> **Fixed**
\* Required

Add appropriate padding to grid columns in task details

---

src/routes/TaskDetails/TaskNotes.jsx
src/routes/__fixtures__/variableInstanceStatusComplete.fixture.json
src/routes/__tests__/TaskDetailsPage.test.jsx

This PR removes the unwanted "Property delete changed from false to true" note that is displayed for a completed task.
**JIRA Ticket**: https://support.cop.homeoffice.gov.uk/browse/COP-9557
- Go to the completed tab and view the details of this task: **CERB-CERB-RORO-Tourist:CMID=TEST-MRUOCCO-1**.
- In another tab, load up the cerberus dev, navigate to the completed tab and load up the task mentioned above.
- Compare the displayed task notes between the local dev environment and cerberus dev environment.
- Compare notes of all other completed tasks.
> Local Dev Env
> Cerberus Dev Env
\* Required

COP-9557 Remove "Property delete changed from false to true"

---

src/routes/__fixtures__/operationsHistoryResponse_PROPERTY_CHANGED.fixture.json
src/routes/__fixtures__/operationsHistoryResponse_USER_CLAIM.fixture.json
src/routes/__fixtures__/operationsHistoryResponse_USER_UNCLAIM.fixture.json
src/routes/__tests__/TaskNotes.test.jsx

- New tests for TaskNotes
- Check that the notes form renders/hides when `displayForm` is true/false
- Check that the `variableInstance` (`history/variable-instance`) data displays correctly in the activity bar
- Check that the `operationsHistory` (`history/user-operation`) data displays correctly in the activity bar
- Check that the `taskHistory` (`history/task`) data displays correctly in the activity bar
- Added some fixtures to support these tests
\* Required

CB 1766: Add more tests for TaskNotes component

---

src/routes/__assets__/TaskDetailsPage.scss

This PR fixes a bug where responsive columns would not maintain their width on window resize.
- Resize the window and confirm that task details columns maintain their width upon window resize.
\* Required

COP-9551 - Fix responsive column width on screen/ window resize

---

src/routes/__assets__/TaskListPage.scss

This PR removes the extra shadow applied to task list cards when the mouse hovers over the task list card.
- Pull and run aginst dev
- Confirm that hovering over each task list card does not activate the hover shadow (images for comparison attached below)
> With hover shadow
> Without hover shadow
\* Required

Remove hover state for task list items

---

src/routes/TaskLists/TaskListPage.jsx

Bug discovered whereby filters were not clearing when 'clear filter' clicked after a page refresh (see test scenario below)
- discovered localStorage returned 'null' as string which was causing the issue
- updated IF condition to handle that
- select a mode filter
- click apply
- refresh page
- click clear filter
- > tasks should reset back to 'all' (default setting)
\* Required

COP-9661 Handle localStorage returning null as string for hasSelectors

---

cypress/integration/cerberus/task-management.spec.js
cypress/support/commands.js

Add tests to verify empty task list fallback message on task management page
execute test `Should check empty task list fallback message on task management page` from spec `task-management.spec.js`
\* Required

COP-4762: Add tests to verify empty task list fallback message on task management page

---

src/routes/TaskDetails/TaskSummary.jsx
src/routes/TaskLists/TaskListMode.jsx
src/routes/__assets__/TaskDetailsPage.scss

This PR adds a cosmetic padding to the RoRo vehicle icons & the RoRo freight movement icon.
- On Task List Page, confirm that there is a visible separation between the icon on the left side of the task summary and the text to the right of it.
- On Task List page, confirm that there is a visible separation between the icon on the right side of the task summary and the text to the left of it.
- On Task Details Page, confirm that there is a visible separation between the icon on the left side of the task summary and the text to the right of it.
- On Task Details page, confirm that there is a visible separation between the icon on the right side of the task summary and the text to the left of it.
\* Required

Add padding to vehicle icons in task list & details page

---

src/routes/TaskDetails/TaskSummary.jsx
src/routes/TaskLists/TaskListMode.jsx
src/routes/TaskLists/TaskListPage.jsx
src/utils/__fixtures__/roroData.fixture.js
src/utils/__fixtures__/roroDataDriverPassengers.fixture.js
src/utils/__tests__/passengersGenerator.test.jsx
src/utils/__tests__/roroDataUtil.test.jsx
src/utils/passengersGenerator.jsx
src/utils/roroDataUtil.jsx

This PR fixes a bug where the driver object in `roroData` was being ignored in the total count of RoRo passengers being returned for the following.
RoRo Tourist: 
- Car
- Foot Passenger
- Group Passengers.
This PR also adds the driver if present, to the passengers array.
- Pull and Run against dev
- Load up cerberus dev in a separate browser tab.
- Locate the task: `CHARLES-2022-01-05-3` on the task list page
- Compare the count of foot passengers between that shown on task list page and that shown on task details page.
\* Required

Cop 9782 - Single foot passenger logic fix

---

cypress/integration/cerberus/filter-tasks-by-pre-arrival-mode.spec.js

Add test for following scenario,
1.) Tick box for RoRo unacc filter
2.) Click on apply filters
3.) Refresh page
4.) Click on clear filters
5.) Tab counts & results are updated
run test `Should retain applied filter after page reload & navigating between pages` from spec `filter-tasks-by-pre-arrival-mode.spec.js`
\* Required

COP-9661: Add test for Multi-select modes persist selection on page refresh

---

cypress/fixtures/taskInfo-known/RoRo-Acc-TaskDetails-expected.json
cypress/fixtures/taskInfo-unknown/RoRo-Acc-VehOnly-expected.json
cypress/fixtures/taskInfo-unknown/RoRo-Acc-VehWithTrail-expected.json
cypress/integration/cerberus/issue-a-target.spec.js
cypress/integration/cerberus/task-details.spec.js
cypress/support/commands.js

Add test to verify 'Property delete changed from false to true' removed from activity log
Fix failing tests due to the latest changes.
run all tests from spec `task-details.spec.js`
\* Required

COP-9557: Add test to verify 'Property delete changed from false to true' removed from activity log

---

cypress/integration/cerberus/filter-tasks-by-selectors.spec.js

Update automation tests to verify selector filter count next to filter name
run all the tests from spec `filter-tasks-by-selectors.spec.js`
\* Required

COP-9367: Update tests to verify selector filter count next to filter name

---

src/routes/TaskDetails/TaskSummary.jsx
src/routes/TaskDetails/TaskVersions.jsx
src/routes/TaskLists/TaskListMode.jsx
src/utils/__fixtures__/roroData.fixture.js
src/utils/__tests__/roroDataUtil.test.jsx
src/utils/__tests__/stringConversion.test.js
src/utils/roroDataUtil.jsx
src/utils/stringConversion.js

This PR (part of a spike) looks at making sure the text displayed in Task Details summary matches the icon displayed.
- Pick a task for `RoRo Accompanied`, `RoRo Unaccompanied`, `RoRo Tourist`, check that the movement mode icon matches the text displayed in task details.
- For RoRo Accompanied (with vehicle & trailer): It should say `Vehicle with Trailer`
- For RoRo Accompanied (with vehicle, no trailer): It should say `Vehicle`
- For RoRo Unaccompanied (with trailer, no vehicle): It should say `Trailer`
- For RoRo Tourist (with vehicle): It should say `Vehicle`
- For RoRo Tourist (single passenger): It should say `1 foot passenger`
- For RoRo Tourist (group): It should say `X foot passengers` <- `x` being any value greater than 1
\* Required

COP-9845 - Check icon text matched icon displayed

---

src/routes/TaskLists/TaskListPage.jsx
src/routes/__tests__/TaskListPage.test.jsx
src/routes/__tests__/TaskListPageFilters.test.jsx

COP-9796: Filters and selectors are showing counts based on selection criteria
1. Select any tab(New, In progress, Issued, Complete) on tasklist page.
2. Select various filters & selectors, click on Apply filters button to see the rendered counts for each filter and selector from the API
3. Clicking on Clear all filters link would reset the count for the selected tab
\* Required

Cop 9796 enabled filtering counts

---

cypress/fixtures/RoRo-Tourist-muliple-passengers.json
cypress/fixtures/RoRo-Tourist-single-passengers.json
cypress/fixtures/tourist-task-with-multiple-passengers.json
cypress/fixtures/tourist-task-with-single-passenger.json
cypress/fixtures/tourist-task-with-vehicle-details.json
cypress/integration/cerberus/create-tasks.spec.js
cypress/integration/cerberus/task-version-details.spec.js

Add tests to verify following scenarios,
For RoRo Tourist (By Car) Show: (No change)
Column 1: Targeting Indicators | Vehicle
Column 2: Booking and check-in
Column 3: Occupants | Driver
For RoRo Tourist (single foot passenger) show: 
Remove "driven by" - "Single passenger"
Column 1: Targeting Indicators (Hide vehicle section)
Column 2: Booking and check-in
Column 3: Primary traveller
For RoRo Tourist (group passengers) show: 
Column 1: Targeting Indicators / Primary traveller /Document
Column 2: Booking and check-in
Column 3: Other travellers 
execute following tests from spec `task-version-details.spec.js`
`Should verify task details of RoRo-Tourist with Vehicle`
`Should verify task details of RoRo-Tourist with Single Passenger`
`Should verify task details of …

COP-9745: Add tests to verify task details of tourist types

---

cypress/integration/cerberus/task-details.spec.js
cypress/integration/cerberus/task-version-details.spec.js
cypress/support/commands.js

Add test to verify the following scenario,
Scenario: Complete task updated
Given a task is 'complete'
When an update is received
Then the task is displayed in the 'New' tasks tab
AND it is displayed as "Updated"
AND all task details/versions/comments/activity are displayed
AND the task is no longer visible in the 'complete' tab
run test `Should complete assessment of a task with a reason as take no further action` from spec `task-details.spec.js`
\* Required

COP-8703: Add tests to verify Display updated tasks that had previously completed assessment

---

cypress/integration/cerberus/task-details.spec.js

Add test to verify Stop users from adding comments in progress when not assigned to them
run test `Should hide Notes Textarea for the tasks assigned to others` from spec `task-details.spec.js`
\* Required

COP-9843: Update test to verify Stop users from adding comments in progress when not assigned to them

---

cypress/fixtures/task-version-passenger/RoRo-task-v1.json
cypress/fixtures/task-version-passenger/RoRo-task-v2.json
cypress/fixtures/task-version-passenger/RoRo-task-v3.json
cypress/integration/cerberus/create-tasks.spec.js
cypress/integration/cerberus/task-version-details.spec.js

Add test to verify following scenario,
GIVEN a task has one or more version
WHEN the task details are displayed
THEN the highest threat level is displayed for each version
GIVEN A task version no longer has a rule/selector match
WHEN the task details are displayed
THEN the version displays "NO RULE MATCHES"
run test `Should verify task Display highest threat level in task details` from spec `task-version-details.spec.js`
\* Required

COP-9672: Add test to verify each version in the task details Display Highest threat level

---

src/govuk/Table.jsx
src/routes/TaskDetails/TaskVersions.jsx
src/routes/__fixtures__/taskVersions.js
src/routes/__tests__/TaskVersions.test.jsx

- Added new `Table` component
- Render risk indicators table at the bottom of each rule match, if they exist. The title of this field should be `Risk indicators (X)`
- If not, only render `Risk indicators (0)`
- Created a very simple test for this
- Updated a fixture for the test
- Run the UI, click on a task and scroll down to the `Rules matched` section. By default, each should have a `Risk indicators (0)` title.
- Add a line after TaskVersions:119, updating `firstRule.childSets` with some input data and toggle `firstRule.hasChildSets` to `true`. If done correctly, this should render the table with the correct data.
- Run the UI, click on a task and the risk indicators' data should be displayed in the `Risk indicators (X)` field.
\* Required

COP 9617: Render risk indicators for rule matches

---

cypress/integration/cerberus/create-tasks.spec.js

Add test to verify the following scenario,
Scenario: NOT RoRo Tourist: no Vehicle (or trailer)
GIVEN a NON RoRo Tourist task
AND it does not have any vehicles or trailers
WHEN the task is displayed in the task list
THEN NO icon is displayed
run test `Should create a task with a payload contains vehicle value as null` from spec `create-tasks.spec.js`
\* Required

COP-9674: Add test to verify No icon displayed if Vehicle node is Empty & non RoRo Tourist task

---

cypress/integration/cerberus/filter-tasks-by-pre-arrival-mode.spec.js
cypress/integration/cerberus/filter-tasks-by-selectors.spec.js
cypress/support/commands.js

Automation tests update to verify the following scenarios
Scenario: view STATUS task list (Replace the word STATUS with the status's below)
GIVEN the STATUS task list tab contains tasks from RBT and SBT
WHEN the targeter views the STATUS task list tab
THEN the number of STATUS tasks containing no selectors is displayed next to the "no selectors" filter
AND the number of STATUS tasks containing selectors is displayed next to the "Selectors" filter
STATUS: "New"; "In-Progress"; "Target Issued"; "Complete"
run all tests in the  following 2 specs
`filter-tasks-by-selectors.spec.js`
`filter-tasks-by-pre-arrival-mode.spec.js`
\* Required

COP-9796: Update tests to adapt latest changes for task Filters

---

src/routes/TaskLists/TaskListPage.jsx

This PR changes the text displayed for the task outcome label in the completed tab in task list page.
**JIRA Ticket**:https://support.cop.homeoffice.gov.uk/browse/COP-9553
- Navigate to the **COMPLETED** tab
- If a **COMPLETED** task has an `outcome` in the payload it will be rendered as a label under the task title (see screenshot below)
>A missed outcome should now say `MISSED TARGET` instead of `MISSED`
>A positive outcome should now say `POSITIVE EXAM` instead of `POSITIVE`
>A negative outcome should now say `NEGATIVE EXAM` instead of `NEGATIVE`
- If a **COMPLETED** task does not have an `outcome` , no label is rendered (see screenshot below)
\* Required

COP-9553 - Rename the target outcome text fix

---

cypress/fixtures/RoRo-task-v1.json
cypress/fixtures/RoRo-task-v2.json
cypress/fixtures/RoRo-task-v3.json
cypress/fixtures/expected-risk-indicators-versions.json
cypress/fixtures/expected-risk-indicators.json
cypress/fixtures/tasks-with-rules-selectors/task-selectors-rules.json
cypress/integration/cerberus/task-management.spec.js
cypress/integration/cerberus/task-version-details.spec.js
cypress/support/index.js
package-lock.json
package.json
src/utils/__fixtures__/taskSummaryData.fixture.js

Add tests to verify Risk Indicators on Rule matches section
GIVEN a task has matched rules
WHEN the task details are viewed
THEN the "Risk indicators" are displayed as the prototype for EACH matched rule
run the test `Should check selector & rule matches details on task management page` from `task-management.spec.js`
`Should verify single task created for the same target with different versions when payloads sent without delay` from `task-version-details.spec.js`
\* Required

COP-9617: Add tests to verify Risk Indicators on Rule matches section

---

src/config.js
src/routes/__tests__/TaskVersions.test.jsx

This PR updates the config used by dayjs.
- Pick a task and go into task details.
- In the task summary located in the `grey box` to the upper section of the page, it should now say `Arrival X hour|hours|day|days|year|years|month|months ago`
\* Required

COP-9967 - Update dayjs config for relative past time

---

cypress/integration/cerberus/filter-tasks-by-selectors.spec.js

Add check to verify Any selector filter selected by default
run the following tests from spec `filter-tasks-by-selectors.spec.js`
`Should apply filter tasks by selectors on newly created tasks`
`Should apply filter tasks by selectors on In Progress tasks`
`Should apply filter tasks by selectors on Issued tasks`
`Should apply filter tasks by selectors on Completed tasks`
\* Required

COP-9956: Add check to verify Any selector filter selected by default

---

cypress/fixtures/RoRo-Unaccompanied-RBT-SBT.json
cypress/fixtures/accompanied-task-2-passengers-details.json
cypress/fixtures/unaccompanied-task-details.json
cypress/integration/cerberus/issue-a-target.spec.js
cypress/support/commands.js

Add tests to verify the following scenario,
Scenario : Task contains haulier details
Given a task contains details of a haulier
WHEN the Target information Sheet is displayed
THEN the "haulier" Checkbox is selected AND
the fields for recording haulier details are displayed
execute the following 2 tests from spec `issue-a-target.spec.js`
`Should submit a target successfully from a RoRo-accompanied task and it should be moved to target issued tab`
`Should submit a target successfully from a RoRo-Unaccompanied task and it should be moved to target issued tab`
\* Required

COP-9847: Add tests to verify auto populated haulier section on TIS

---

cypress/integration/cerberus/issue-a-target.spec.js

Add tests for following 2 scenarios
Scenario 1:Do not show account questions for RoRo Tourist
GIVEN a task is a RoRo task
WHEN the TIS is displayed
THEN the account questions are NOT displayed
Scenario 2: DO show them for RoRo Freight (accompanied and unaccompanied)
GIVEN a task is a RoRo Freight (accompanied and unaccompanied)
WHEN the TIS is displayed
THEN the account questions are displayed
run all the tests from spec `issue-a-target.spec.js`
\* Required

COP-9846 : Add tests to verify Account details auto populated for RoRo Frieght tasks

---

cypress/fixtures/accompanied-task-no-passengers.json
cypress/integration/cerberus/issue-a-target.spec.js

Add test to verify Passenger information hidden on TIS
Scenario 1: View task with passengers in TIS
Given a task has passengers
WHEN the Target Information sheet is displayed
THEN the passenger fields are displayed
Scenario 2: View task withOUT passengers in TIS
Given a task has NO passengers
WHEN the Target Information sheet is displayed
THEN the passenger fields are NOT displayed
run first 4 tests from spec `issue-a-target.spec.js`
\* Required

COP-9852: Add test to verify Passenger information hidden on TIS

---

src/routes/TaskDetails/TaskVersionsMode/SectionRenderer.jsx
src/routes/__tests__/TaskVersionsMode/SectionRenderer.test.jsx

This PR adds back the previously removed rendering of entity search URLS when they were present.
- Pull & Run against dev
- In the `NEW` tab, locate the task `ROROTSV:CMID=MRUOCCO-ENTITY-SEARCH-TEST-3`
- Under the occupants section, if there is an entity search URL present, the name of the occupant will be rendered as a link.
\* Required

Entity search fix

---

src/routes/TaskLists/TaskListPage.jsx
src/routes/__tests__/TaskListPage.test.jsx

This PR adds the highest-threat-level sorting parameter to the task list page for tasks that are IN_PROGRESS or NEW
\* Required

add highest threat level sorting filter

---

src/routes/__tests__/TaskVersions.test.jsx
src/utils/__tests__/roroDataUtil.test.jsx
src/utils/roroDataUtil.jsx

This PR is a minor fix which swaps out the previously used `eta` datetime value for the `departure` datetime used to calculate the relative time difference for the check-in time (an error reported by one of the SMEs).

COP-9849 - Swaps out previously used eta value for scheduled departure time

---

cypress/fixtures/selectors-group-expected.json
cypress/fixtures/selectors-group-versions-expected.json
cypress/fixtures/tasks-with-rules-selectors/RoRo-task-selectors-same-group-reference.json
cypress/fixtures/tasks-with-rules-selectors/RoRo-task-selectors-v1-same-group-reference.json
cypress/fixtures/tasks-with-rules-selectors/RoRo-task-selectors-v2-diff-group-reference.json
cypress/integration/cerberus/task-details.spec.js
cypress/support/commands.js

Add tests to verify Selectors grouping with global reference ID
Scenario : 
Scenario 1: Multiple selectors in the same selector group
GIVEN a task has multiple selectors with the same Group reference ID
WHEN I view the task details
THEN the Group reference details are displayed in the Task details
AND the multiple selectors with the same group reference are displayed under this
run the following tests from spec `task-details.spec.js`
`Should verify the selector matches with same group reference`
`Should verify the selector matches with same & different group reference on 2 different version of a task`
\* Required

COP-8641: Add tests to verify Selectors grouping with global reference ID

---

cypress/integration/cerberus/task-details.spec.js

Update test to accept enter key when adding comment for a task
run the test `Should add notes for the selected tasks` from spec `task-details.spec.js`
\* Required

COP-9934: Update test to accept enter key when adding comment for a task

---

cypress/integration/cerberus/task-management.spec.js
cypress/support/commands.js

Generate tasks with different selectors and rules for sorting
run the test `Should verify tasks are sorted in correct order selectors with highest category should be at top of the list on task management page` 
check the tasks sorted by the rules given in COP-9955
Notes: it is not possible to verify the sorting tasks with selectors and rule as there always be different other tasks available.
\* Required

COP-9955: Generate tasks with different selectors and rules for sorting

---

src/routes/TaskDetails/TaskVersionsMode/SectionRenderer.jsx
src/routes/__assets__/TaskDetailsPage.scss
src/routes/__fixtures__/section-renderer/sectionRendererTaskDetails.js
src/routes/__tests__/TaskVersionsMode/SectionRenderer.test.jsx

This PR handles the scenario where unknown counts could be null. Initially would display `Nan` if null. This fix does not render the section if this is the case.
- In dev environment load this task [https://www.dev.cerberus.cop.homeoffice.gov.uk/tasks/COKAFOR-10-03-2022-RORO-Accompanied-Freight-NO-OCCUPANT-COUNTS-WITH-UNKNOWN-COUNT_391435:CMID=TEST](url)
- Locally load this task [http://localhost:8080/tasks/COKAFOR-10-03-2022-RORO-Accompanied-Freight-NO-OCCUPANT-COUNTS-WITH-UNKNOWN-COUNT_391435:CMID=TEST](url)
`Outcome`: If unknown count is null, it should not render the section all together.
\* Required

COP-10007 - Handles null values from unknown count

---

src/routes/TaskDetails/TaskVersionsMode/SectionRenderer.jsx
src/routes/__tests__/TaskVersionsMode/SectionRenderer.test.jsx

This PR replaces the field name displayed in the Booking & check-in section of any movement mode.
- Pull & run against dev.
- Select any task, regardless of it's movement mode.
- Verify that the fields highlighted in the image shown below now says
- **FOR:** `Date and time` **REPLACED WITH:** `Booking date and time`
- **FOR:** `Check-in` **REPLACED WITH:** `Check-in date and time`
\* Required

OP-10255 - Replaces field names for date and time & check-in

---

src/routes/TaskDetails/TaskVersions.jsx
src/routes/__tests__/TaskVersions.test.jsx

This PR changes the headers used within the `Rules Matched` section in task details page.
- Find a task with rules matched e.g. [http://localhost:8080/tasks/Shakir-Demo-15-02-2022-Selector-different-versions-task_541666:CMID=TEST](url) and open it
Anywhere we have  headers: **`Type`** | **`Condition 1`** | **`Expression`** | **`Condition 2`**
Will now be replaced with the following headers: **`Entity Type`** | **`Attribute`** | **`Operation`** | **`Value(s)`**
\* Required

COP-10248 - Changes heading under rule matched in task versions

---

cypress/integration/cerberus/issue-a-target.spec.js
cypress/support/commands.js

Add tests to verify the following scenario
Scenario 1: Issue target
GIVEN I am completing the Target Information Sheet
WHEN I view the "Recipient Details" page
THEN there is an option to alert the frontline if the vehicle may appear in either lane - "Inform both Freight and Tourist"
run the following tests from spec `issue-a-target.spec.js`
`Should submit a target successfully from a RoRo-Tourist task and it should be moved to target issued tab`
`Should submit a target successfully from a RoRo-accompanied task and it should be moved to target issued tab`
`Should submit a target successfully from a RoRo-Unaccompanied only with Trailer task and it should be moved to target issued tab`
\* Required

COP-9803: Add tests to verify option to alert the frontline if the vehicle may appear in either lane

---

cypress/fixtures/RoRo-Freight-Accompanied.json
cypress/fixtures/RoRo-Tourist-2-passengers.json
cypress/fixtures/RoRo-Tourist-RBT-SBT.json
cypress/fixtures/RoRo-Unaccompanied-RBT-SBT.json
cypress/fixtures/accompanied-task-2-passengers-details.json
cypress/fixtures/tourist-task-co-travellers.json
cypress/fixtures/tourist-task-details.json
cypress/fixtures/unaccompanied-task-details.json
cypress/integration/cerberus/create-tasks.spec.js
cypress/integration/cerberus/task-version-details.spec.js
cypress/support/commands.js

Add tests for checking Enrichment count for different modes of tasks
Scenario 1: Entity in Task details with previous movements
GIVEN an entity has had previous movements
WHEN the entity is displayed in the task details
THEN the number of previous movements/Examinations/Seizures is displayed under the heading
An entity can be an Driver/Lead passenger, Occupant, Vehicle, Trailer, Haulier, Account
run the following tests from spec `task-version-details.spec.js`
`Should verify task version details of unaccompanied task on task details page`
`Should verify task version details of tourist task on task details page`
`Should verify task version details of accompanied task with 2 passengers on task details page`
run the following test from `create-tasks.spec.js` to check the counts of a task with …

COP-10250: Add tests for Aggregated counts in the task list

---

src/utils/__tests__/roroDataUtil.test.jsx
src/utils/roroDataUtil.jsx

This PR displays the category counts on a task in task details. This information is rendered for either a RoRo Accompanied Freight | RoRo Tourist movement.
The category are rendered based on the following conditions:
Scenario 1
Has driver: FALSE
Has passenger(s): FALSE
Has category counts: TRUE
Outcome: SHOW CATEGORY COUNTS
Scenario 2
Has driver: TRUE
Has passenger(s): FALSE
Has category counts: TRUE
Outcome: SHOW CATEGORY COUNTS
Scenario 3
Has driver: FALSE
Has passenger(s): FALSE
Has category counts: FALSE
Outcome: SHOW UNKNOWN COUNTS ONLY
Scenario 4
Has driver: TRUE
Has passenger(s): TRUE
Has category counts: TRUE | FALSE
Outcome: DO NOT SHOW CATEGORY COUNTS
\* Required
- …

COP-10625: fixes occupants counts not showing up

---

src/routes/roro/TaskDetails/TaskSummary.jsx
src/routes/roro/TaskLists/TaskListMode.jsx
src/utils/__tests__/roroDataUtil.test.jsx
src/utils/getVehicleModeIcon.jsx
src/utils/roroDataUtil.jsx

This PR address an bug where within a movement, we would get 2 persons however, one of them just has empty fields which was throwing off the logic that generated which icon that was to be displayed.
- Locate any RoRo foot passenger/ passengers task.
- The movement mode icon should match the number of people in the movement (the information displayed on the task list card on task list page e.g. `Single passenger` & `1 foot passenger` should match with that which is also displayed within the `TaskSummary` block on task details page)
-  **AND** it should also match with the number of people within that movement.
- A good example of the bug is this task https://www.dev.cerberus.cop.homeoffice.gov.uk/tasks/CERB-MRUOCCO-PASSENGER-TEST-1 which actually has only 1 …

COP-10677 - movement mode icon mismatch

---

src/utils/__tests__/roroDataUtil.test.jsx
src/utils/roroDataUtil.jsx

This PR address a bug found in **STAGING** whereby if we were to receive an invalid country code such as **UN**, the task details page would fail to load.
\* Required

COP-10724 - Handles blank page load error when country code is invalid - Patch#2

---

src/utils/__tests__/calculateDatetimeDifference.test.js
src/utils/calculateDatetimeDifference.js

This PR adds a `suffix` option to the current time difference calculator method. This PR will be going back into an ongoing feature branch.
\* Required

Adds the suffix to the time difference calculation

---

webpack.config.js

The application will fail to start without specifying a `FILE_UPLOAD_API_URL` parameter when attempting to run it. This defaults the value to an empty string, which will allow it to start up locally without an issue, although, obviously, files will not successfully be uploaded.
Related to https://support.cop.homeoffice.gov.uk/browse/COP-10219.
Try running the application locally without specifying a `FILE_UPLOAD_API_URL` parameter. If it starts up fine, it can be considered to have passed the test.
\* Required

COP-10219: Allow missing upload service url

---

src/constants.js
src/routes/airpax/__fixtures__/targetListData.js
src/routes/airpax/__fixtures__/taskData_AirPax_AssigneeCurrentUser.fixture.json
src/routes/airpax/__fixtures__/taskData_AirPax_AssigneeOtherUser.fixture.json
src/routes/airpax/__fixtures__/taskData_AirPax_NoAssignee.fixture.json
src/routes/airpax/__fixtures__/taskData_AirPax_TargetIssued.fixtures.json
src/routes/airpax/__fixtures__/taskData_AirPax_TaskComplete.fixture.json
src/routes/airpax/__fixtures__/taskData_AirPax_TaskDetails.fixture.json
src/routes/airpax/__tests__/__snapshots__/TaskVersions.test.jsx.snap
src/routes/airpax/__tests__/builder/Itinerary.test.jsx
src/routes/airpax/__tests__/builder/Passenger.test.jsx
src/routes/airpax/__tests__/builder/__snapshots__/Itinerary.test.jsx.snap
src/routes/airpax/__tests__/utils/BookingUtil.test.js
src/routes/airpax/__tests__/utils/DateTimeUtil.test.js
src/routes/airpax/__tests__/utils/MovementUtil.test.js
src/routes/airpax/__tests__/utils/__snapshots__/MovementUtil.test.js.snap
src/routes/airpax/utils/datetimeUtil.js
src/routes/airpax/utils/movementUtil.jsx

This PR refactors the frontend code to properly render the departure status.
> Supplemental
This PR also refactors the datetime utils to use UTC timezone instead of BST timezone.
A **majority** of this PR is just code updates due to time changes as well as the change to the departure status due to how it is now returned from the backend. Nothing new has been added.
\* Required

COP-10838 - Updates Front end to render departure status

---

cypress.json
cypress/fixtures/airpax/airpax-expected-response.json
cypress/fixtures/airpax/task-airpax.json
cypress/integration/airpax/create-aipax-tasks.spec.js
cypress/support/commands.js

This PR has changes to create airPax tasks from cypress and checking it on UI.
run the following command to port forward the request
`kubectl --context=acp-notprod_COP --namespace=cop-cerberus-dev port-forward service/cop-targeting-api 9443:443`
update the `cerberusServiceUrl` to `localhost:9443` in cypress.json
select `create-aipax-tasks.spec.js` from folder `airpax` and run them.
\* Required

Setup automation tests for airpax tasks

---

cypress/integration/airpax/airpax-task-details.spec.js
cypress/support/commands.js

Add tests for checking action buttons on task details page.
Test added for following 2 scenarios
If the task is assigned to a user, only that user can see these buttons.
If the task is not assigned to a user, then the user cannot see these buttons.
execute tests from spec `airpax-task-details.spec.js`
`Should see all the action buttons if task claimed by the same user`
`Should verify all the action buttons not available for non-task owner`
\* Required

COP-10876: Add tests for checking action buttons on task details page

---

src/routes/airpax/TaskDetails/builder/CoTraveller.jsx
src/routes/airpax/__tests__/__snapshots__/TaskVersions.test.jsx.snap

This PR hides the movement details URL normally rendered along other co-travellers
**BEFORE:**
**AFTER:**
\* Required

COP-10463 - Hides the movement details link displayed next other travellers

---

cypress/fixtures/airpax/task-airpax.json
cypress/integration/airpax/airpax-task-overview-page.spec.js
src/routes/airpax/__tests__/__snapshots__/TaskVersions.test.jsx.snap

Add tests for claim / unclaim airpax task 
All scenarios covered given in the ticket, 
https://support.cop.homeoffice.gov.uk/browse/COP-10470
run the tests from spec `airpax-task-overview-page.spec.js`
`Should Unclaim a task assigned to me Successfully from In Progress tab and verify it moved to New tab`
`Should Unclaim a task assigned to another user Successfully verify it moved to New tab`
\* Required

COP-10470: Add tests for claim / unclaim airpax task

---

cypress/fixtures/airpax/task-airpax-latest.json
cypress/fixtures/airpax/task-airpax.json
cypress/integration/airpax/airpax-task-overview-page.spec.js

Add tests to verify User journey of dismissing an airpax task.
run the tests from spec `airpax-task-overview-page.spec.js`
`Should dismiss a task with a reason`
`Should dismiss a task with a reason and without notes`
Note:  Test `Should dismiss a task with a reason` is failing at the moment because clicking on `Cancel` button during dismiss not taking back to the task details page & returns 500 error response.
\* Required

COP-10474: Add tests for dismissing  Airpax task

---

src/components/RenderForm.jsx
src/components/__tests__/RenderForm.test.jsx
src/constants.js
src/cop-forms/dismissTaskCerberus.js
src/routes/airpax/TaskDetails/TaskDetailsPage.jsx

As form renderer does not have a mechanism of cancelling a form, this PR adds an implementation of cancelling the dismiss a task form.
- Claim an airpax task
- Click on the **`Dismiss`** action button
- Clicking on the **`Cancel`** button will cause the page to reload, exiting the form.
\* Required

COP-10949 - Handle form cancellation

---

cypress/integration/airpax/airpax-task-overview-page.spec.js

Display the NEW label in the overview section on task details page for only NEW
Run - npm run cypress:runner airpax-task-overview-page.spec.js
"Should display new label for new tasks on task details and not display new label when it is claimed"
\* Required

Cop 10912  : Display new label for new tasks on task details

---

cypress/integration/airpax/airpax-task-details.spec.js
cypress/support/commands.js

Update / add tests foe PNR view permission
run the following tests from spec  `airpax-task-details.spec.js`
`Should check airPax task not visible if User not agreed for PNR terms`
`Should check airPax task not visible if User not in the authorised location`
\* Required

COP-10984 : Update / add tests foe PNR view permission

---

cypress/integration/airpax/task-list-page.spec.js

Add test to validate UPDATE label is displayed, when a task is updated
https://support.cop.homeoffice.gov.uk/browse/COP-10953
Should not display UPDATED label on a new task, but display UPDATED after a task has been updated with new details
\* Required

COP-10953 : Add test to validate UPDATE label is displayed when a task is updated

---

cypress/fixtures/airpax/airpax-task-expected-details.json
cypress/integration/airpax/airpax-task-details.spec.js

Add tests to verify Co-travellers details of AirPax task
run the test from spec `airpax-task-details.spec.js`
`Should verify Co-traveller details of an AirPax task on task details page`
\* Required

COP-10463: Add tests to verify Co-travellers details of AirPax task

---

src/constants.js
src/routes/airpax/TaskDetails/builder/Booking.jsx
src/routes/airpax/TaskDetails/builder/CoTraveller.jsx
src/routes/airpax/utils/bookingUtil.jsx
src/routes/airpax/utils/datetimeUtil.js
src/routes/airpax/utils/movementUtil.jsx
src/routes/roro/TaskDetails/TaskSummary.jsx
src/routes/roro/TaskLists/TaskListMode.jsx
src/utils/DatetimeUtil.js
src/utils/__tests__/DatetimeUtil.test.js
src/utils/__tests__/stringConversion.test.js
src/utils/stringConversion.js

This PR fixes the relative time text bug on the roro task details and task list page. The appropriate text is returned along with the time calculated by `dayjs` library.
- On the task list page, if a task has already arrived, part of the summary text will say `...arrived 3 years ago`.
- On the task list page, if a task is due to arrive, part of the summary text will say `...arriving in 3 years`.
- The above applies to task details page task summary.

Fixes RoRo relative time bug on task summary

---

src/context/PnrAccessContext.jsx
src/index.jsx
src/routes/access/PnrAccessRequest.jsx
src/routes/airpax/TaskLists/TaskListPage.jsx
src/routes/airpax/TaskLists/TasksTab.jsx
src/routes/airpax/__tests__/TaskListPage.test.jsx
webpack.config.js

This PR address a minor bug where if the `cop-targeting-api` returns an empty array when the user has said they do not want to view PNR data, the button which allows the user to resubmit a justification is not rendered.

Pnr access request (bug fix)

---

cypress/integration/airpax/airpax-task-details.spec.js

Add tests to verify the PNS access control message
run the following tests from spec `airpax-task-details.spec.js`
`Should check airPax task not visible if User not agreed for PNR terms`
`Should check airPax task not visible if User not in the authorised location`
\* Required

COP-10478: Add tests to verify the PNS access control message

---

cypress/integration/airpax/filter-airpax-tasks-by-ruleID.spec.js

Add test to check there are not duplicate rules returned from API / ve/filters/rules
run the test
`Should apply filter tasks by different rule ID on newly created tasks`
\* Required

COP-10948: Add test to check duplicate rules

---

cypress/fixtures/RoRo-tourist-v2.json
cypress/fixtures/RoRo-unaccompanied-v2.json
cypress/fixtures/airpax/airpax-expected-response.json
cypress/integration/airpax/airpax-task-details.spec.js
cypress/integration/airpax/airpax-task-overview-page.spec.js
cypress/integration/airpax/create-aipax-tasks.spec.js
cypress/integration/airpax/filter-airpax-tasks-by-ruleID.spec.js
cypress/integration/airpax/task-list-page.spec.js
cypress/integration/cerberus/archive-RoRo-tasks.spec.js
cypress/integration/cerberus/create-tasks.spec.js
cypress/support/commands.js

Add test to Forward RORO movement records from cop targeting api to cerberus workflow service
npm run cypress:test -- --spec cypress/integration/cerberus/create-tasks.spec.js
Should create a Roro-Accompanied task from Cop-targetting API and forward to Cerberus workflow service
Should create a Roro-Unaccompanied task from Cop-targetting API and forward to Cerberus workflow service
Should create a Roro-Tourist task from Cop-targetting API and forward to Cerberus workflow service
\* Required

Cop 10921: Add test to Forward RORO movement records from cop targeting api to cerberus workflow service

---

cypress/integration/airpax/airpax-task-overview-page.spec.js

Add test for Update wording on assessment complete & dismiss task options.
npm run cypress:test:local -- --spec cypress/integration/cerberus/airpax-tasks-overview-page.spec.js
Should complete a task with a reason'
Should dismiss a task with a reason
\* Required

COP-11197: Add test for Update wording on assessment complete & dismiss task options.

---

cypress/fixtures/airpax/airpax-task-expected-details.json
cypress/fixtures/airpax/task-airpax-singlePassenger.json
cypress/integration/airpax/airpax-task-details.spec.js

Add test for Remove main traveller row from co-travellers table
https://support.cop.homeoffice.gov.uk/browse/COP-11199
npm run cypress:test:local -- --spec cypress/integration/airpax/airpax-tasks-details.spec.js
Should verify Co-traveller details not available for an AirPax task with a single passenger on task details page
\* Required

COP-11199 Add test for Remove main traveller row from co-travellers table

---

cypress/fixtures/airpax/issue-task-airpax.json
cypress/integration/airpax/filter-airpax-tasks-by-TaskId-or-Passenger.spec.js
cypress/integration/airpax/issue-aipax-tasks.spec.js
cypress/support/commands.js

Add test for Submit target information sheet
https://support.cop.homeoffice.gov.uk/browse/COP-11198
npm run cypress:test:local -- --spec cypress/integration/airpax/issue-airpax-tasks.spec.js
Should submit a target successfully from an AirPax task
\* Required

COP-11198 : Add test for Submit target information sheet

---

src/cop-forms/completeTaskCerberus.js
src/cop-forms/dismissTaskCerberus.js
src/routes/airpax/TaskDetails/TaskDetailsPage.jsx
src/routes/airpax/__tests__/TaskDetailsPage.test.jsx
src/routes/roro/TaskDetails/TaskDetailsPage.jsx
src/routes/roro/__tests__/TaskDetailsPage.test.jsx

This PR hides the `Notes` form when the user clicks the `Issue target`, `Assessment complete` & `Dismiss` buttons (RoRo & AirPax).
- Within the optional notes form which allows the user to enter additional notes, the `?` that was initially on the `Add a note?` label has been removed.
- Click either `Issue target`, `Assessment complete` or `Dismiss task` button
- The notes form will be hidden.

COP-10787 - Hide notes form

---

src/routes/airpax/TaskDetails/builder/CoTraveller.jsx
src/routes/airpax/__tests__/__snapshots__/TaskVersions.test.jsx.snap
src/routes/airpax/__tests__/builder/__snapshots__/CoTraveller.test.jsx.snap

This PR adds the document number within the co-travellers table.
- Load any airpax task with co-travellers.
- Within the co-travellers table, if a co-traveller has a document number, it is now displayed (see screenshot below)

COP-111346 - Document number (co-travellers table)

---

src/components/RenderForm.jsx
src/constants.js
src/routes/airpax/TaskDetails/TaskDetailsPage.jsx
src/routes/airpax/__tests__/utils/TargetInformationUtil.test.js
src/routes/airpax/utils/targetInformationUtil.js

This PR changes the logic at which stage the form data is temporarily stored to handle error events which can happen within the form renderer (including the consuming application), to avoid user loosing the data contained within the form (both auto population data and options selected by the user).
- Claim a task
- Click on `Issue target`
- The form loaded will contain pre-population data, add more to the form by filling in more data.
- There are two ways to simulate an error within the form 
- One way would be to wait at least  15+ minutes after filling out the mandatory fields
- Another would be to fill out the mandatory fields and perform a page refresh.
- If you opt for the first option, on submitting the form, an error will be thrown however, observe that the …

COP-11362 - Form data storage

---

src/routes/airpax/TaskDetails/TaskDetailsPage.jsx
src/routes/airpax/__fixtures__/targetData_AirPax_PrefillData.json
src/routes/airpax/__tests__/utils/TargetInformationUtil.test.js
src/routes/airpax/utils/targetInformationUtil.js

This PR addresses a bug shown in the screenshot below where the multi select would not be properly populated with values from RefData when attempting to modify the form data but it would appear as expected on the CYA screen.
- Load up this task (https://www.dev.cerberus.cop.homeoffice.gov.uk/airpax/tasks/DEV-20220725-399) and claim it.
- On the `Selection details` section of the form, click on the `Change` link next to the right of the `Targeting indicators` header.
- It should now take you back to the selection details and the multi select autocomplete should be properly populated.

COP-11392 - Targeting indicators bug

---

cypress/integration/airpax/airpax-task-overview-page.spec.js

Add test for User should be prompted to save notes during assessment complete
npm run cypress:test:local -- --spec cypress/integration/airpax/airpax-task-overview-page.spec.js
Should validate Add notes section is hidden in Issue target, Assessment complete and Dismiss task
\* Required

COP-10787: Add test for User should be prompted to save notes during assessment complete

---

cypress/fixtures/airpax/airpax-task-expected-details.json
cypress/fixtures/airpax/task-airpax-coTraveller-document-unknown.json
cypress/integration/airpax/airpax-task-details.spec.js
cypress/integration/airpax/filter-airpax-tasks-by-TaskId-or-Passenger.spec.js

Add test for Add document number against each co-traveller
npm run cypress:test:local -- --spec cypress/integration/airpax/airpax-tasks-details.spec.js
Should verify Document number in document column for Co-traveller if present
\* Required

COP-11346: Add test for Add document number against each co-traveller

---

src/routes/roro/TaskDetails/TaskVersionsMode/EnrichmentCount.jsx
src/routes/roro/TaskLists/EnrichmentCount.jsx
src/routes/roro/TaskLists/TaskListMode.jsx
src/routes/roro/__tests__/TaskVersionsMode/__snapshots__/SectionRenderer.test.jsx.snap

This PR hides the enrichment counts rendered on the task list page & task details page.
- Go to the RoRo task list
- On the **task list** page, the enrichment counts (shown in the screenshot below) will not be rendered on each task list card
- On the **task details** page, the enrichment headers including the counts (shown in the screenshot below) will not be rendered on screen e.g.

COP-10789 - Hide Enrichment Count

---

cypress/integration/airpax/filter-airpax-tasks-by-selectors.spec.js
cypress/integration/cerberus/issue-a-target.spec.js
cypress/support/commands.js

Add test for Port dropdown not showing all RoRo ports
npm run cypress:test:local -- --spec cypress/integration/cerberus/issue-a-target.spec.js
Should verify event ports are available in target information sheet
\* Required

COP-11335: Add test for Port dropdown not showing all RoRo ports

---

cypress/integration/cerberus/task-details.spec.js

Added test for Aggregated counts table to be hidden in COP Cerberus UI
npm run cypress:test:local -- --spec cypress/integration/cerberus/tasks-details.spec.js
Should verify aggregated count table is hidden in task list and task overview page
\* Required

COP-10789-test: Added test for Aggregated counts table to be hidden in COP Cerberus UI

---

src/components/RenderForm.jsx
src/constants.js
src/context/ApplicationContext.jsx
src/routes/airpax/TaskDetails/TaskDetailsPage.jsx
src/routes/airpax/__tests__/TaskDetailsPage.test.jsx
src/routes/airpax/__tests__/utils/TargetInformationUtil.test.js
src/routes/airpax/utils/targetInformationUtil.js
src/utils/Form/uploadDocuments.js

This PR changes how we are temporarily caching the prefill data from the form in the event of submission failure. 
Initially was being stored in local storage however `file` data (uploaded images) cannot be serialised hence the change to context.

COP-11456 - Form data caching

---

package-lock.json
package.json
src/components/RenderForm.jsx
src/components/__tests__/RenderForm.test.jsx
src/routes/airpax/TaskDetails/TaskDetailsPage.jsx
src/routes/airpax/utils/targetInformationUtil.js

Code refactoring to pass a cancel action to the newly added onCancel hook within the form renderer.
This PR also fixes the incorrectly generated `nominalChecks` node within the submission payload.

COP-11477 - onCancel action

---

src/components/__tests__/RenderForm.test.jsx
src/config.js
src/routes/airpax/__tests__/TaskListPageFilters.test.jsx
src/routes/roro/TaskLists/TasksTab.jsx
src/utils/__tests__/axiosInstance.test.js
src/utils/axiosInstance.js
src/utils/keycloak.jsx

Pull & run against dev.
1. Load the task list page and monitor the Network tab
2. Don't do anything on task list page for 15 minutes
3. The new token would be fetched from keycloak and subsequent API calls would be using the refreshed token to get the data
1. Claim the task on task list page on Airpax mode
2. Click issue target to see cya page
3. Fill all required fields clicking on change link
4. Wait for token to be refreshed (15 minutes)
5. Click on Accept and send button to submit the TIS
\* Required

COP-11412: getting refreshed keycloak token after expiry

---

cypress/fixtures/airpax/airpax-TIS-details.json
cypress/integration/airpax/airpax-task-details.spec.js
cypress/integration/airpax/issue-aipax-tasks.spec.js

Added test for Code refactor in relation to the spike for form cancellation
npm run cypress:test:local -- --spec cypress/integration/airpax/aipax-tasks-details.spec.js
Should cancel issue target successfully but still retail auto populated values in target information sheet
\* Required

Cop 11477: Added test for Code refactor in relation to the spike for form cancellation

---

src/__assets__/_utilities.scss
src/routes/airpax/TaskLists/TaskListPage.jsx
src/routes/roro/TaskLists/TaskListPage.jsx

On Task Management Page
The Filters(Mode & Selectors) on tasklist page would stick and always be visible to the user while scrolling
\* Required

COP-11414: Made filters sticky on task management page

---

src/constants.js
src/routes/airpax/TaskDetails/TaskDetailsPage.jsx
src/routes/airpax/TaskDetails/builder/Document.jsx
src/routes/airpax/__tests__/TaskDetailsPage.test.jsx
src/routes/airpax/__tests__/__snapshots__/TaskVersions.test.jsx.snap
src/routes/airpax/__tests__/utils/DocumentUtil.test.js
src/routes/airpax/utils/datetimeUtil.js
src/routes/airpax/utils/documentUtil.js
src/routes/roro/TaskDetails/TaskDetailsPage.jsx
src/routes/roro/__tests__/TaskDetailsPage.test.jsx

This PR hides the action buttons `Issue Target`, `Assessment complete` & `Dismiss` when any of these is selected which leads to a form rendering.
This PR also adds a missed behaviour where on form cancellation is triggered, a confirmation dialog is displayed to the user to confirm their action.
- Claim a task
- Clicking on each action button should hide all action buttons.
- Clicking on the cancel button should trigger a confirmation dialog that asks the user to confirm their decision.

COP-11453 - Hide action button

---

cypress/integration/airpax/airpax-task-details.spec.js
cypress/integration/airpax/filter-airpax-tasks-by-assignedToMe.spec.js
cypress/support/commands.js

Added test for When the weight is blank, we can still see the kg being displayed in the weight section.
npm run cypress:test:local -- --spec cypress/integration/airpax/airpax-task-details.spec.js
Should verify Baggage details of an AirPax task
\* Required

COP-10955: Added test for When the weight is blank, we can still see the kg being displayed in the weight section

---

src/routes/TaskList/components/roro/TouristMovementSection.jsx

This PR addresses a bug which comes about when a task (mainly in RoRo V2 as we can have a tourist task with multiple people) has multiple co-travellers. Somehow the previous code has gone from returning a `JSX` object to returning a `JSX` object that is now wrapped within another object which then causes the UI to trip over itself.
- Post a Tourist task (group/ vehicle) with multiple persons in the movement.
- Access the RoRo V2 task list page, the UI will then trip over itself.

Fixes code which returns object of a jsx object instead of the jsx object

---

src/components/RenderForm/RenderForm.jsx
src/routes/TaskDetails/TaskDetailsPage.jsx
src/routes/TaskList/TaskListPage.jsx

This PR fixes a bug introduced when a page does not contain the required pieces of data for it to make a network call.
Adds a newly added prop **`viewOnly`** to the form renderer (stops the error summary giving the impression that the prefill data has been wiped out).

COP-10856 - Adds conditional post params based on view
