UKHomeOffice/cerberus-service

- package-lock.json
- package.json
- src/assets/styles/main.scss
- src/index.html
- webpack.config.js
Add govuk frontend design system
- Pull the branch locally;
- Run the project;
- Go to localhost:8080 and you should see the govuk icon in the tab;
- Open the developer console and you should also see the required css being loaded from the govuk design system;
\* Required
> Add govuk frontend

- package-lock.json
- package.json
- src/components/App/Header.jsx
- src/config/core.js
- src/index.html
- src/index.jsx
- src/reducers/index.js
- src/routes.jsx
- webpack.config.js
Wrap structure in keycloak auth.
- Pull the branch locally;
- Install dependencies;
- Run the project;
- Go to `http://localhost:8080` and you should be redirected to keycloak login page;
- Login with O365, and you should see the menu;
\* Required
> COp-4489: Wrap structure in keycloak auth

- babel.config.json
- jest.setup.jsx
- package-lock.json
- package.json
- src/forms/FieldInput.jsx
- src/forms/Form.jsx
- src/forms/formContext.js
- src/forms/useField.js
- src/forms/useForm.js
- src/routes/IssueTargetPage.jsx
1. Start the app
2. Navigate to http://localhost:8080/issue-target
3. Check if the form values are stored by pressing the submit button
\* Required
> COP-4093: Create forms engine

- package-lock.json
- package.json
- src/__assets__/index.scss
- src/assets/styles/main.scss
- src/index.html
- src/index.jsx
- webpack.config.js
Allow importing styles in react components.
1. Run `npm i`
2. Test if everything works as before
\* Required
> COP-4093: Allow to import styles in react components

- src/govuk/Button.jsx
- src/govuk/SecondaryButton.jsx
Add components for GDS primary and secondary button:
https://design-system.service.gov.uk/components/button/
These components are not yet used in the app (PR is coming).
\* Required
> COP-4093: Add Button and SecondaryButton components

- src/govuk/ErrorMessage.jsx
- src/govuk/FormGroup.jsx
- src/govuk/Hint.jsx
- src/govuk/Label.jsx
Add component for GDS form group, hint, label and error message.
This component is not yet used in the app (PR is coming).
\* Required
> COP-4093: Add FormGroup component with dependencies

- jest.config.js
- src/__mocks__/assetMock.js
- src/forms/Form.jsx
- src/forms/LoadingSpinner.jsx
- src/forms/__assets__/LoadingSpinner.scss
- src/forms/__tests__/LoadingSpinner.test.jsx
- src/routes/IssueTargetPage.jsx
Add component used to indicate loading.
2. Submit the form
3. You should see a loading indicator
\* Required
> COP-4093: Add LoadingSpinner component

- src/forms/Form.jsx
- src/forms/useField.js
- src/forms/useForm.js
Persist the form data until the form is submitted or cancelled.
2. Fill some fields
3. Refresh the page
4. All the entered values should be still there
5. Clicking the "Submit" button should clear the values
\* Required
> COP-4093: Persist form data until the submission

- src/forms/Form.jsx
- src/forms/FormErrors.jsx
- src/govuk/ErrorSummary.jsx
- src/routes/IssueTargetPage.jsx
Show error summary component when for validation fails.
2. Submit the form without filling any of the required fields
3. You should see error summary at the top
\* Required
> COP-4093: Show error summary when form validation fails

- src/forms/FieldInput.jsx
- src/govuk/Input.jsx
- src/routes/IssueTargetPage.jsx
Add input field that uses styles from GDS.
2. Check if the input field looks like the field from GOV.UK Design System: https://design-system.service.gov.uk/components/text-input/
\* Required
> COP-4093: Add text input compatible with GDS

- src/forms/FormActions.jsx
- src/forms/FormBack.jsx
- src/forms/FormProgress.jsx
- src/forms/FormStep.jsx
- src/forms/__assets__/FormActions.scss
- src/routes/IssueTargetPage.jsx
Introduce component for multistep forms.
2. Click "Save and continue"
3. You should see second form step
4. Clicking "< Back" should bring you to the first step
\* Required
> COP-4093: Enable multistep forms

- src/forms/FieldInput.jsx
- src/forms/FieldSelect.jsx
- src/forms/FormStep.jsx
- src/forms/useField.js
- src/forms/useForm.js
Remove field value when a field is removed from the DOM, navigating between steps will preserve the form value.
1. Go to the "Issue target form"
2. Fill the form and navigate to the next step
3. Go back
4. The value should be preserved
5. Optionally, modify the code to check if the value is removed when a specific condition is met, e.g.
```
{values.test === 'hello' && <FieldInput name="test2" type="text" label="Test input 2" />}
```
\* Required
> COP-4093: Clear field value when a conditional field component is unmounted

- src/forms/FieldRadios.jsx
- src/govuk/Fieldset.jsx
- src/govuk/FormGroup.jsx
- src/govuk/Label.jsx
- src/govuk/Radios.jsx
- src/govuk/Select.jsx
- src/routes/IssueTargetPage.jsx
Add component used to render radios.
1. Go to the "Issue target form"
2. Check if the radios component is displayed and it looks same as the GDS one https://design-system.service.gov.uk/components/radios/
3. Changing the selection should update the values and the field should validate
\* Required
> COP-4093: Add FieldRadios component

- jest.setup.jsx
- src/forms/FieldAddress.jsx
- src/forms/__tests__/FieldAddress.test.jsx
- src/forms/__tests__/validators.test.jsx
- src/forms/useField.js
- src/forms/validators.js
- src/routes/IssueTargetPage.jsx
Add address field component.
1. Go to the "Issue target form"
2. Check if the elements for the address field are displayed
\* Required
> COP-4093: Add FieldAddress

- package-lock.json
- package.json
- src/forms/FieldAutocomplete.jsx
- src/forms/useField.js
- src/govuk/Autocomplete.jsx
- src/govuk/FormGroup.jsx
- src/govuk/__assets__/Autocomplete.scss
- src/routes/IssueTargetPage.jsx
Add an autocomplete field
1. Run `npm start`
2. Go to the "Issue target form"
3. Check if the dropdown "Test autocomplete" displays the results as you type/select
\* Required
> COP-4093: Add autocomplete field

- src/forms/FieldAutocomplete.jsx
- src/forms/FieldTextarea.jsx
- src/forms/__tests__/FieldTextarea.test.jsx
- src/govuk/Input.jsx
- src/govuk/Textarea.jsx
- src/routes/IssueTargetPage.jsx
Add textarea field based on GDS component.
1. Open the `Issue a target form`
2. You should see a textarea field
\* Required
> COP-4093: Add FieldTextarea

- src/forms/FieldCheckboxes.jsx
- src/govuk/Checkboxes.jsx
- src/govuk/Radios.jsx
- src/govuk/__tests__/Checkboxes.test.jsx
- src/routes/IssueTargetPage.jsx
Add component used to render checkboxes.
1. Go to the "Issue target form"
2. Check if the checkboxes component is displayed and it looks similar as the GDS one https://design-system.service.gov.uk/components/checkboxes/
3. Changing the selection should update the values and the field should validate
\* Required
> COP-4093: Add FieldCheckboxes component

- src/__assets__/_base.scss
- src/__assets__/index.scss
- src/components/Header.jsx
- src/govuk/Tabs.jsx
- src/routes/TaskListPage.jsx
- src/routes/__fixtures__/tasks.js
- src/routes/index.jsx
Add a tabs component compatible with GDS.
1. Go to the tasks page
2. You should see tabs
\* Required
> COP-5191: Add Tabs component

- src/govuk/Accordion.jsx
- src/govuk/Details.jsx
- src/govuk/__tests__/Accordion.test.jsx
- src/routes/TaskDetailsPage.jsx
- src/routes/TaskListPage.jsx
- src/routes/__fixtures__/tasks.js
- src/routes/index.jsx
Add the GDS accordion component with a basic task details page.
1. Click "Tasks" nav link
2. Click the first task
3. You should see an accordion
\* Required
> COP-5191: Add Accordion with basic task details page

- .eslintrc.js
- README.md
- cypress.json
- cypress/fixtures/users/cypressuser@lodev.xyz.json
- cypress/integration/cerberus/login.spec.js
- cypress/support/commands.js
- cypress/support/index.js
- package-lock.json
- package.json
This PR has initial setup for Cypress Test Automation for Cerberus UI.  It has a simple test for Sign-in with key-cloak credentials. 
then run the login.spec.js
\* Required
> COP-5461: Setup Cypress Test Automation for Cerberus UI

- package-lock.json
- package.json
- src/__assets__/_base.scss
- src/components/Layout.jsx
- src/routes/TaskDetailsPage.jsx
- src/routes/__assets__/TaskDetailsPage.scss
- src/routes/__fixtures__/tasks.js
- src/routes/index.jsx
Complete the task details page to match the prototype with mocked data.
1. Go to the `Tasks` page
2. Click the first task
3. You should see a task details page that looks the same as the prototype (check the ticket)
\* Required
> COP-5191: Complete mocked task details page

- .drone.yml
- env.yaml
- kube/deployment.yml
> COP-4506 removed tests until ready

- .drone.yml
> cop-4506 renamed master to main

- .drone.yml
> COP-4506 removed _ from name

- .drone.yml
- kube/deployment.yml
> COP-4506 added missing port config and cleaned up deployment

- kube/deployment.yml
> COP-4506 fixed typo

- kube/deployment.yml
> Cop 4506 pipeline fix

- kube/ingress.yml
> cop-4506 fixed ingress

- Dockerfile
- README.md
- nginx/run.sh
Fix the Docker build by using the correct index file from the `dist` folder.
\* Required
> Fix docker container

- .drone.yml
- kube/deployment.yml
> COP-4506 added protocol and deploy auto on push to master

- src/__assets__/_formio.scss
- src/__assets__/index.scss
- src/routes/IssueTargetPage.jsx
- webpack.config.js
Fix minor CSS issues on the target sheet form.
1. Go to the target sheet form
2. You should see a form that looks like a general form build using GDS components
\* Required
> COP-5403: Small fixes to the target sheet form

- .eslintrc.js
- jest.config.js
- package-lock.json
- package.json
- src/components/Pagination.jsx
- src/components/__assets__/Pagination.scss
- src/forms/FieldDateTime.jsx
- src/forms/__tests__/LoadingSpinner.test.jsx
- src/govuk/DateInput.jsx
- src/govuk/__tests__/DateInput.test.jsx
- src/routes/TaskDetailsPage.jsx
- src/routes/TaskListPage.jsx
- src/routes/__fixtures__/tasks.js
- src/utils/formioSupport.js
Add ability to browse paginated tasks.
1. Run `npm i`
2. Go to task list
3. You should see mocked tasks with pagination at the top
\* Required
> COP-5121: Add pagination to task list

- .drone.yml
Add drone steps to:
* run unit-tests
* run linter
Once you create a PR you should see that drone now runs all unit-tests as well as the linter for the entire project folder
\* Required
> Update drone build with unit-tests and linter steps

- package.json
- src/components/Pagination.jsx
- src/constants.js
- src/routes/TaskDetailsPage.jsx
- src/routes/TaskListPage.jsx
- src/routes/__assets__/TaskListPage.scss
- src/routes/__fixtures__/tasks.js
1. Run `npm i`
2. Go to the task list page
3. The page should look similar to the prototype except filters and selection
\* Required
> COP-5121: Update task list page

- .eslintrc.js
- cypress/integration/cerberus/task-management.spec.js
This PR has tests for checking pagination on task list page.
select cypress/integration/cerberus/task-management.spec.js
\* Required
> COP-5770: Add tests for pagination on task list page

- cypress/integration/cerberus/login.spec.js
This PR has changes foe the login test to adapt the landing page.
choose login.spec.js
\* Required
> COP-5900: Update test to adapt the landing page

- .drone.yml
- env.yaml
- kube/deployment.yml
> COP-5990 Added Requested Env Vars

- Dockerfile
- nginx/nginx.conf
- nginx/run.sh
- src/config.js
- src/routes/IssueTargetPage.jsx
- src/routes/TaskDetailsPage.jsx
- src/routes/TaskListPage.jsx
- src/utils/axiosInstance.js
- webpack.config.js
Update the codebase to use the real data instead of fixtures.
1. Go to the task list
2. Tasks should render
\* Required
> Use camunda API to fetch tasks

- .drone.yml
- env.yaml
> COP-6015 cerberus service to forms-api

- src/forms/__assets__/LoadingSpinner.scss
- src/routes/IssueTargetPage.jsx
- src/utils/formioSupport.js
1. Go to the TIS form
2. Submit the form
3. The submission should land in Camunda
\* Required
> COP-4358: Submit target information sheet

- README.md
- src/govuk/ErrorSummary.jsx
- src/routes/TaskDetailsPage.jsx
- src/routes/TaskListPage.jsx
1. Go to the task list
2. Task should render
3. Click on any task from the list
4. Task details should render
\* Required
> COP-4082: Update task list and task details pages to use task ID

- src/govuk/LinkButton.jsx
- src/govuk/__assets__/LinkButton.scss
- src/routes/IssueTargetPage.jsx
- src/routes/TaskDetailsPage.jsx
1. Go to the task details page
2. Click "Claim" link
3. Page should refresh and a task should be assigned to you
4. Clicking "Unclaim" should remove the assignment
\* Required
> COP-4082: Claiming a task

- src/routes/TaskDetailsPage.jsx
- Should be able to add a note to a specific task
- You should then be able to query said task, and see all notes attached to it (via postman, insomnia etc.)
- Run locally
- Open network tab
- Navigate to single task page
- Enter text in the notes box
- Click `Save`
- *You should see a `create` request made in the network tab return with a 200 response*
- *You should see the form clear the input text and serve a new empty notes form*
\* Required
> COP-5053 Add task notes functionality

- .drone.yml
- README.md
- cypress/config/dev.json
- cypress/config/local.json
- cypress/integration/cerberus/login.spec.js
- cypress/integration/cerberus/task-management.spec.js
- cypress/plugins/index.js
- package-lock.json
- package.json
This PR:
* enables the tests to run against Local & Dev environments using config file;
* adds step in the drone.yml to run the tests against Dev environment inside drone server.
Refer README document to run the tests.
\* Required
> COP-5721 : Setup tests to run across local & Dev environments

- src/components/ClaimTaskButton.jsx
- src/govuk/__assets__/LinkButton.scss
- src/routes/TaskDetailsPage.jsx
- src/routes/TaskListPage.jsx
1. Go to the task list
2. Click "Claim" link
3. Page should refresh and a task should be assigned to you
4. Clicking "Unclaim" should remove the assignment
\* Required
> COP-4081: Claim task from the task list

- src/routes/TaskDetailsPage.jsx
1. Go to the task details page
2. You should see the activity log in the right-bottom corner
\* Required
> COP-5056: Show task activity log

- .drone.yml
As per https://github.com/UKHomeOffice/cerberus-service/pull/78 , I am adding the cypress tests running against dev back into the drone.yml
\* Required
> Add run_test_dev step back into drone.yml

- .drone.yml
- env.yaml
> cop-6207 added preliminary drone sit deployment

- .drone.yml
- nginx/nginx.conf
As the dev environment was working briefly after deployment, we are removing nginx caching to test if this is the issue
\* Required
> Remove nginx proxy caching

- .drone.yml
Adding drone tests back in after fixing nginx
\* Required
> Add drone tests back in

- src/components/ClaimTaskButton.jsx
- src/components/RenderForm.jsx
- src/govuk/Panel.jsx
- src/routes/IssueTargetPage.jsx
- src/routes/TaskDetailsPage.jsx
- src/routes/TaskListPage.jsx
- src/utils/axiosInstance.js
- src/utils/formioSupport.js
1. Go to the task list
2. Claim one of the tasks
3. Open the claimed task 
4. Click "Assessment complete"
5. Submit the form
6. You should see a confirmation message and the task should no longer be accessible
1. Go to the task list
2. Claim one of the tasks
3. Open the claimed task 
4. Click "Dismiss"
5. Submit the form
6. You should see a confirmation message and the task should no longer be accessible
\* Required
> COP-5502: Add task complete and dismiss forms

- cypress/integration/cerberus/task-details.spec.js
- cypress/integration/cerberus/task-management.spec.js
- kube/deployment.yml
This is purely for testing purposes
\* Required
> Remove protocol from proxy service

- .drone.yml
> COP-6207 added sync secrets for sit

- cypress/integration/cerberus/task-details.spec.js
- cypress/integration/cerberus/task-management.spec.js
It has tests for Claim task from task management & details page.
Claim a task & check it is assigned and Camunda end-point returns 204 response code
run task-details.spec.js & task-management.spec.js 
\* Required
> COP-6256: Add tests for claim tasks from Task details & Task management Page

- env.yaml
Add Cerberus user credentials in secrets
N/A
\* Required
> COP-6435: Add Cerberus user credentials in secrets

- env.yaml
- kube/secret.yml
Add secrets in yml file
N/A
\* Required
> COP-6435: Add secrets in yml file

- src/govuk/Tabs.jsx
- src/routes/TaskDetailsPage.jsx
- src/routes/TaskListPage.jsx
1. Go to the task management page
2. Clicking the "New" tab should only display the unassigned tasks
3. Clicking the "In progress" tab should only display the tasks that have someone assigned to them
4. Clicking the "Completed" tab should only display the completed tasks
\* Required
> COP-4761: Render the completed tasks tab

- .drone.yml
> Updated drone.yml with required changes for staging and prod deployment

- src/constants.js
- src/routes/IssueTargetPage.jsx
- src/routes/TaskDetailsPage.jsx
- src/utils/formioSupport.js
This PR is to refactor how we submit forms on cerberus, it also now includes the `form` object in the request payload so that payloads are stored in S3
- Pull and run cerberus natively
- Submit an issue a target form from navbar
- *Should submit form successfully*
- Submit a note against a task
- *Should submit a note successfully*
\* Required
> Refactor form submissions

- nginx/nginx.conf
Set resolver and proxy timeout in nginx config to fix issues with the proxy endpoint for Camunda.
\* Required
> Update NGINX config to fix proxy issues

- nginx/nginx.conf
Fix nginx proxy by updating the proxy_pass setting
\* Required
> Update nginx proxy_pass setting

- nginx/nginx.conf
> Moved resolver to http block

- src/routes/TaskDetailsPage.jsx
This PR allows for form submissions to progress through the workflow correctly. In doing so, it allows the works for COP-4671 to be completed.
- Pull and run natively - have chrome dev tools open for duration of testing
- Claim task from task list
- Navigate to claimed task
- Submit issue target form
- *You should see `actionTarget` be equal to true in the request payload*
- Repeat this process for each form in the task details page with both Dismiss and Complete Assessment forms having `actionTarget` equal to false
\* Required
> COP-4671 Correct actionTarget value in form payload

- src/routes/TaskListPage.jsx
Renaming `task` to `targetTask` to be more accurate
\* Required
> Change name of variable 'task' to 'targetTask'

- src/routes/TaskListPage.jsx
Reverts UKHomeOffice/cerberus-service#118
Reverting as tasks on dev are no longer displaying and unclear if it is this PR or the refresh of task data
> Revert "Change name of variable 'task' to 'targetTask'"

- src/routes/TaskListPage.jsx
Updated task to targetTask
Updated taskCount to targetTaskCount
to make it easier to distinguish what sort of task it's referring to
\* Required
> COP-4592 Update variables to be clearer

- src/routes/TaskDetails/TaskDetailsPage.jsx
- src/routes/TaskLists/TaskListPage.jsx
- src/routes/__tests__/TaskDetailsPage.test.jsx
- src/routes/__tests__/TaskListPage.test.jsx
- src/routes/index.jsx
Move files into folder structure so we can break down into components
\* Required
> Move pages into folders

- nginx/nginx.conf
- nginx/run.sh
> Nginx upstream proxy

- nginx/nginx.conf
- nginx/run.sh
Reverts UKHomeOffice/cerberus-service#110
> Revert "Nginx upstream proxy"

- src/routes/TaskDetails/TaskVersions.jsx
This PR removes all `TODO` placeholder text until the correct data to be displayed has been provided.
- Navigate to a single task
- Expand the task version
- *You should not see `TODO` anywhere on the page*
\* Required
> COP-6673 Remove todos from task details

- nginx/nginx.conf
> Modifications to nginx timeout

- nginx/nginx.conf
> Removed keepalive_time unsupported by this version of nginx

- package-lock.json
- package.json
- src/constants.js
- src/routes/TaskDetails/TaskDetailsPage.jsx
- src/routes/TaskDetails/TaskVersions.jsx
- src/routes/TaskLists/TaskListPage.jsx
- src/utils/formatTaskSummaryData.js
**Moment.js** is now a legacy project, and therefore we decided to update or code to make use of **Day.js** library to parse and manipulate dates, specially since **Day.js** uses the same **API** as moment.
* clone repo;
* run project (native development or with docker)
* run all tests and ensure none breaks due to moment being replaced;
* quickly run the app in your localhost and check if the dates look accordingly.
\* Required
> COP-6432: Replace Momentjs with Dayjs

- src/utils/__fixtures__/taskSummaryData.fixture.js
Previous fixture file had absolute time difference. I have updated the fixture to use relative time difference
- Pull and run tests
- *They should pass*
\* Required
> Change task summary fixture to use relative time

- nginx/nginx.conf
- nginx/run.sh
> COP-6966 Added upstream without resolve and keepalive

- nginx/nginx.conf
- nginx/run.sh
> COP-6966 fixed server details

- nginx/nginx.conf
> COP-6966 have to explicitly port to 443 for upstream

- nginx/nginx.conf
> COP-6966 fixed upstream paths by using different server calls

- nginx/nginx.conf
> COP-6966 reset dns settings

- nginx/nginx.conf
> Re-enabled server directive with redirects

- nginx/nginx.conf
> COP-6966 setting host via variable causes 404 issues

- nginx/nginx.conf
> COP-7112 improving logging output

- cypress/integration/cerberus/issue-a-target.spec.js
- cypress/integration/cerberus/task-details.spec.js
- cypress/support/commands.js
issue-a-target-spec.js test updated with adding nominal type data in the TIS form.
select issue-a-target-spec.js and run
\* Required
> COP-6563: Add test for adding nominal data in the target information sheet form

- kube/deployment.yml
sticky plaster as discussed to healthcheck the nginx pod's proxy config and deal with current timeout issues occuring over time
\* Required
> add liveness probe

- cypress/integration/cerberus/issue-a-target.spec.js
Fix failing test (issue-a-target.spec.js) to adapt ref-data changes.
execute issue-a-target.spec.js tests
\* Required
> Update test to adapt ref-data changes

- cypress/integration/cerberus/issue-a-target.spec.js
Change target receive group to Portsmouth team
choose `issue-a-target.spec.js` and run
\* Required
> COP-7501: Change target receive group to Portsmouth team

- scripts/run-tests.sh
ConfigFile option needs to be removed as all the configs removed.
N/A
\* Required
> Remove configFile option for test runner

- cypress/plugins/index.js
BaseUrl should be picked up from the secrets. It was defaulting to localhost:8080
N/A
\* Required
> Fix baseUrl default to localhost:8080

- src/components/ClaimTaskButton.jsx
- src/routes/TaskDetails/TaskDetailsPage.jsx
- src/routes/TaskLists/TaskListPage.jsx
- src/routes/__tests__/TaskDetailsPage.test.jsx
- src/routes/__tests__/TaskListPage.test.jsx
- src/routes/index.jsx
This PR changes the task detail url to use the business key and not the process instance id
- Select a target from new tab
- *You should be taken to the target page successfully*
- *The information should appear correctly in line with what was received in camunda*
- Select a target from the Complete tab
- *You should be taken to the target page successfully*
- *The information should appear correctly in line with what was received in camunda*
- (Test against task versioning instance if possible)
\* Required
> COP-5748 Task hyperlink

- src/routes/TaskDetails/TaskVersions.jsx
Discovered an empty div being created, this is to move the logic so that doesn't happen
- Open a target
- In the task details section scroll to the driver section
- view the html
- there should not be an empty div as the last item of the list
\* Required
> Move the check if hidden so it does not create an empty div

- src/__assets__/_formio.scss
Added disabled styles to Formio inputs
\* Required
> COP-7030 fix disabled styling for textareas

- cypress/integration/cerberus/formapi-404.spec.js
- cypress/integration/cerberus/issue-a-target.spec.js
- cypress/integration/cerberus/task-details.spec.js
- cypress/integration/cerberus/task-management.spec.js
- cypress/support/commands.js
Tasks generated with businessKey contains  the special characters ( / = :).
Tests update to navigate to the individual tasks which contains businessKey with forward slash.
Please refer the README for the context, namespace and secretName for different env
./scripts/env-setup.sh {context} {namespace} {secretName}
update cypress.env.json with respective url for
"cerberusServiceUrl": "xxx",
"formApiUrl": "xxx",
Check the generated report in the folder, /mochawesome-report
\* Required
> COP-7873: Update tests to have businessKey with forward slash

- cypress/fixtures/RoRo-task-v1.json
- cypress/fixtures/RoRo-task-v2.json
- cypress/fixtures/RoRo-task-v3.json
- cypress/fixtures/task-version/RoRo-task-v1.json
- cypress/fixtures/task-version/RoRo-task-v2.json
- cypress/fixtures/task-version/RoRo-task-v3.json
- cypress/fixtures/task-version/RoRo-task-v4.json
- cypress/integration/cerberus/create-tasks.spec.js
- cypress/integration/cerberus/task-version-details.spec.js
- cypress/support/commands.js
Tests added to verify the task created with different versions for the same target if there are new movement update.
Different scenarios added, sending the update without any delay, with delay and payloads which were causing issues.
Please refer the README for the context, namespace and secretName for different env
./scripts/env-setup.sh {context} {namespace} {secretName}
update cypress.env.json with respective url for
"cerberusServiceUrl": "xxx",
"formApiUrl": "xxx",
run tests from the spec `task-version-details.spec.js`
\* Required
> COP-7949: Add tests for task versioning for new movement update

- README.md
Update README to have current instructions on how to start
\* Required
> Update local start instructions

- src/routes/TaskDetails/TaskVersions.jsx
Identified it was always returning null or invalid due to wrong key used for date/time
\* Required
> COP-7637 Update bookingDate to use correct key

- README.md
- src/routes/TaskDetails/TaskDetailsPage.jsx
- src/routes/TaskDetails/TaskVersions.jsx
In preparation for rewriting how we display taskSummary, this PR tidies up the imports, and updates names of variables to make them more accurately reflect what they contain
- view a target detail page
\* Required
-  [x] Up-to-date with main branch? \*
> COP-8083 Update variable names to make clearer

- src/components/ClaimTaskButton.jsx
- src/govuk/__assets__/LinkButton.scss
- src/routes/TaskDetails/TaskDetailsPage.jsx
- src/routes/TaskDetails/TaskSummary.jsx
- src/routes/TaskLists/TaskListPage.jsx
- src/routes/__assets__/TaskListPage.scss
- src/routes/__fixtures__/taskSummaryData.fixture.json
- src/routes/__fixtures__/variableInstanceStatusComplete.fixture.json
- src/routes/__fixtures__/variableInstanceStatusIssued.fixture.json
- src/routes/__fixtures__/variableInstanceStatusNew.fixture.json
- src/routes/__fixtures__/variableInstanceTaskSummaryBasedOnTIS.fixture.json
- src/routes/__tests__/TaskListPage.test.jsx
- src/routes/__tests__/TaskSummary.test.jsx
We used to use `taskSummary` to populate details of the `TaskList` and `TargetSummary` - however `taskSummary` did not always provide the latest data.
A new variable `taskSummaryBasedOnTIS` has been created with the data we need. This PR updates to use that, and does a little refactoring to tidy things up.
----
Scenarios to look for
- Line 1: `Vehicle` if only vehicle
- Line 1: `Trailer` if only trailer
- Line 1: `Vehicle with Trailer` if both
- Line 2: `<Vehicle registration>` if only vehicle & no driver
- Line 2: `<Trailer registration>` if only trailer & no drive
- Line 2: `<Vehicle registration> with <Trailer registration>` if both & no driver
- Line 2: `<Vehicle registration> driven by <driver name>` if only vehicle & driver
- Line 2: `<Trailer registration> driven by <driver name>` …
> COP-8083 Update source of task summary and task list data

- src/routes/TaskDetails/TaskVersions.jsx
This PR allows the full rendering of the selectors in the taskDetails object
- Submit payload to dev environment with selectors in the payload (as many as you like)
- Go to the business key under the submitted payload in the cerberus ui
- *You should see all the fields rendered on the screen (pertinent to the ticket)*
\* Required
> COP-7942 Improved Selector match display

- src/routes/TaskDetails/TaskDetailsPage.jsx
Discovered after merging to dev that businessKey location has changed, this is to update it to the new location
To Test
- click on a target (remember this target url)
- > the latest version should be open
- close the latest version
- refresh the page
- > latest version should stay closed
- go back to target list
- click on a different target
- > latest version should be open
- go to your first target again
- > latest version should be closed (as you left it in a closed state earlier)
- log out
- log in
- go to your first target again
- > latest version should be open (as logging out clears all your states)
\* Required
> Update businessKey location

- cypress/fixtures/task-vehicle-null.json
- cypress/integration/cerberus/create-tasks.spec.js
- cypress/integration/cerberus/task-version-details.spec.js
- cypress/support/commands.js
Test created to check if application handles the payload with vehicle node as null and created the task successfully.
Enabled tests to create tasks when payloads sent parallel and without delay.
npm un cypress:runner
run the following specs,
`cypress/integration/cerberus/create-tasks.spec.js`
`cypress/integration/cerberus/task-version-details.spec.js`
\* Required
> COP-8780: Add test to verify task created when payload contains vehicle node as null

- src/__mocks__/keycloakMock.js
- src/constants.js
Group names need a /
\* Required
> COP-8861 Add / to group name

- cypress/fixtures/RoRo-task-target-indicators.json
- cypress/integration/cerberus/task-version-details.spec.js
Fix failed tests and add additional check for Target Indicators. 
run the following tests from spec  `task-version-details.spec.js`
`Should verify all the target indicators received in the payload displayed on UI`
`Should verify task details on each version retained`
\* Required
> Fix failed tests

- src/routes/TaskDetails/TaskDetailsPage.jsx
- src/routes/TaskDetails/TaskVersions.jsx
- src/utils/__tests__/findAndUpdateTaskVersionDifferences.test.jsx
- src/utils/findAndUpdateTaskVersionDifferences.js
This PR adds the ability to see differences between versions in the task detail page. As well as this, it also adds the number of differences found to each unexpanded task version section
- Find a task with multiple versions
- *It should highlight the differences between the versions correctly*
- *It should produce the correct number of differences in the task version summary*
- Find a task with 1 version
- *It should not have any differences*
\* Required
> COP-8704 Display version differences

- package-lock.json
- package.json
Moderate and High errors in packages that require latest webpack-cli and webpack-dev-service of at least 4.3.1
Updated
pull down
run npm i
start cerberus ui
> it should build and run on localhost:8080
\* Required
> COP-9118 Update webpack

- jest.config.js
- package-lock.json
- package.json
High priority package updates dependent on Jest 27.x
Updated jest package & added test environment to jest config
- run npm i
- run npm test
Test should pass
\* Required
> COP-9118 Update jest

- package-lock.json
nth-check has a vulnerability, it's within renderkid/css-select so updated renderkid to force the update
Run tests - all should pass
\* Required
> COP-9119 Update renderkid to update nth-check which has vulnerability

- cypress/fixtures/RoRo-task-v3.json
- cypress/integration/cerberus/task-version-details.spec.js
Test to Checking difference in each version was updated to verify all the fields in all the sections.
Execute test `Should verify difference between versions displayed on task details page` from spec `task-version-details.spec.js` 
\* Required
> Improve task version difference details test to check all the fields in all the sections

- cypress/fixtures/task-details-versions.json
Fix failed test on Dev due to the latest change in the version data 
run test `Should verify task details on each version retained` from spec `task-version-details.spec.js`
\* Required
> Fix failed test on Dev due to the latest change in the version data

- src/routes/TaskLists/TaskListPage.jsx
- src/routes/__fixtures__/variableInstanceTaskSummaryBasedOnTIS.fixture.json
- src/routes/__tests__/TaskListPage.test.jsx
This PR aims to display the total risk score for each task on the tasks list.
- On the tasts list, each task will have a **Risk score:** along with a value if risk scores are present e.g. **Risk score: 25** and just  **Risk score:** if there's no risk score.
> Cop 9051 - display total risk score

- src/routes/TaskLists/TaskListPage.jsx
This PR focuses on UI element changes.
On task lists page,
- **Goods details** has been changed to **Goods description**
- As this required BE changes, cop-8926 for process-models would need to be approved first and deployed to dev. The expected result is that Haulier section should come BEFORE Account section.
\* Required
> updated task details page

- cypress/integration/cerberus/issue-a-target.spec.js
- cypress/support/commands.js
Update automation tests to issue targets to different groups . 
run all tests from spec `issue-a-target.spec.js`
\* Required
> COP-9347: Update tests to issue target to different groups

- src/routes/TaskLists/TaskListPage.jsx
- src/routes/__assets__/TaskListPage.scss
- src/routes/__fixtures__/variableInstanceTaskSummaryBasedOnTIS.fixture.json
- src/routes/__tests__/TaskListPage.test.jsx
This PR adds an **Updated** badge to tasks in the task list that have multiple versions.
Jira Ticket: [https://support.cop.homeoffice.gov.uk/browse/COP-9246](url)
- When a task has a version number is greater than 1, it will have an **Updated** badge below the task title. 
- For tasks that do not have a version number greater than 1, no badge is rendered.
> Note: See attached picture for example
\* Required
> COP-9246 Highlight updated tasks

- cypress/fixtures/passenger-details.json
- cypress/fixtures/task-version-passenger/RoRo-task-v1.json
- cypress/fixtures/task-version-passenger/RoRo-task-v2.json
- cypress/fixtures/task-version-passenger/RoRo-task-v3.json
- cypress/integration/cerberus/task-management.spec.js
- cypress/integration/cerberus/task-version-details.spec.js
- cypress/support/commands.js
Add tests to verify Back to task list workflow
Update delete automation data method so that it deletes all the data after weekend, check if the day is Monday and subtract 3 days from the current data to delete the tasks.
Add / update tests to check the passenger information on different versions where one of the versions doesn't contain passenger data and other 2 versions have passenger data.
run test `Should verify Back to task list workflow` from spec `task-management.spec.js`.
run following tests from spec `task-version-details.spec.js`
`Should verify single task created for the same target with different versions with different passengers information`
`Should verify passenger details on different version on task details page`
\* Required
> COP-8933: Add tests to verify Back to task list workflow

- cypress/fixtures/tourist-task-2-passengers-details.json
- cypress/integration/cerberus/issue-a-target.spec.js
- cypress/support/commands.js
Add test to verify control strategy multi select drop down
Update RoRO-Tourist issue target test to check if all the fields are populated. 
run all the tests from spec `issue-a-target.spec.js`
\* Required
> COP-9370: Add test to verify control strategy multi select drop down

- cypress/integration/cerberus/task-version-details.spec.js
Update tests with more than one version to check UPDATED displayed on tasklist page.
run all the tests from spec `task-version-details.spec.js`
\* Required
> COP-9246: Update tests with more than one version to check UPDATED displayed on tasklist

- kube/ingress.yml
> CPES239-Ingress-Certs

- kube/ingress.yml
> CPES239-Ingress-v1

- .drone.yml
- kube/ingress.yml
> Cpes239 ingress path

- src/govuk/__assets__/LinkButton.scss
- src/routes/TaskLists/TaskListPage.jsx
- src/routes/__assets__/TaskDetailsPage.scss
- src/routes/__assets__/TaskListPage.scss
- src/routes/__tests__/TaskListPage.test.jsx
This PR updates the task list page UI to **closer** match the one found on the prototype (https://cerberus.prototype.cop.homeoffice.gov.uk/blue/pinned/task-list)
- JIRA Ticker: https://support.cop.homeoffice.gov.uk/browse/COP-9550
- Pull & run against dev.
- Compare the new task list page UI against the current UI.
> **New UI - COP-9550**
vs.
> **Current UI**
> **Please Note:**
> This ticket performs a UI update to closer match that of the prototype. Do note that this UI update omits the following listed below which may be raised in a new ticket at a later date should the need arises.
> - The select All checkboxes.
> - The checkbox next to each task.
> - The icon next to each task
> - The Ship/ Car/ Van icons.
\* Required
> Cop 9550 Task list UI as prototype

- cypress/integration/cerberus/filter-tasks-by-selectors.spec.js
Automation tests updated for following scenario,
Scenario: View task list
GIVEN the task list contains at least one task
When the filters are displayed
Then the options for the "Selector" filter are: 'Present', Not present', 'Any'
run all the tests from spec `filter-tasks-by-selectors.spec.js`
\* Required
> COP-9511: Update select filter names

- cypress/fixtures/RoRo-Accompanied-RBT-SBT.json
- cypress/fixtures/RoRo-Freight-Accompanied.json
- cypress/fixtures/RoRo-Tourist-2-passengers.json
- cypress/fixtures/RoRo-Tourist-RBT-SBT.json
- cypress/fixtures/RoRo-Unaccompanied-Freight.json
- cypress/fixtures/RoRo-Unaccompanied-RBT-SBT.json
- cypress/fixtures/RoRo-task-v1-target-update.json
- cypress/fixtures/RoRo-task-v1.json
- cypress/integration/cerberus/issue-a-target.spec.js
- cypress/support/commands.js
Add tests to verify the category set on TIS
Update payload to contain different combinations of selector categories. 
run all the tests from spec `issue-a-target.spec.js`
\* Required
> COP-9397: Add tests to verify the category set on TIS

- src/routes/TaskLists/TaskListPage.jsx
Testing release candidate branch
\* Required
> Testing release candidate branch

- src/routes/TaskLists/TaskListPage.jsx
> Test release candidate

- src/routes/TaskLists/TaskListPage.jsx
> Remove test text

- src/routes/TaskLists/TaskListPage.jsx
this was added when testing the release-candidate branch and now needs to be removed
\* Required
> Remove test paragraph

- src/routes/TaskLists/TaskListPage.jsx
Task list should be sorted by arrival date ascending
View task list, tasks should be in ascending order by arrival date
\* Required
> COP-9695 Switch sort order to asc

- .drone.yml
- package.json
- sonar-project.properties
https://sonarqube.digital.homeoffice.gov.uk/dashboard?id=cop-cerberus-service
\* Required
> COP-9559 Sonarqube integrated

- .drone.yml
- package.json
- sonar-project.properties
https://sonarqube.digital.homeoffice.gov.uk/dashboard?id=cop-cerberus-service
\* Required
> Sonarqube coverage report

- src/__assets__/_utilities.scss
- src/routes/TaskDetails/TaskVersions.jsx
- src/routes/TaskLists/TaskListPage.jsx
COP-9367: Showing number of tasks for both filters and selectors
1. On task list landing page
2. All filters and selectors showing total counts 
\* Required
> COP-9367: Number of tasks per selector filter

- src/routes/TaskDetails/TaskVersions.jsx
- src/routes/__fixtures__/taskNoRulesMatchData.fixture.json
- src/routes/__fixtures__/taskSingleVersionData.fixture.json
- src/routes/__tests__/TaskNotes.test.jsx
- src/routes/__tests__/TaskVersions.test.jsx
- src/utils/stringConversion.js
Display highest threat level in task details
1. Select a task in any tab state on Task management landing page with selectors/rules
2. The journey would take the user to the Task details page for the selected task
3. Highest threat level Category or Tier would appear for selector/rule
4. If there isn't any selector/rule then No rule matches message would be shown
\* Required
> Cop 9672: Display highest threat level in task details

- src/routes/__fixtures__/variableInstanceStatusComplete.fixture.json
- src/routes/__tests__/TaskDetailsPage.test.jsx
- src/routes/__tests__/TaskNotes.test.jsx
This PR is a quick update of the task notes test.
Pull and run tests, all tests in task notes should not fail
\* Required
> Cb-1766 fix test

- src/routes/__assets__/TaskListPage.scss
COP-9711: Wrapping text heading on multiple lines
1. In In progress tab last task on task list page.
2. The last task heading is wrapped into multiple lines
\* Required
> COP-9711: Wrapping text heading on multiple lines

- cypress/integration/cerberus/task-details.spec.js
Update test to add notes on the task assigned to others
run test `Should add Notes for the tasks assigned to others` from spec `task-details.spec.js`
\* Required
> COP-9318: Update test to add notes on the task assigned to others

- src/routes/TaskLists/TaskListMode.jsx
This PR adds checks for gender retrieval.
\* Required
> Refactor gender retrieval

- src/routes/__fixtures__/roro-tourist-vehicle-3-passengers/taskListData_RoRoTourist.fixture.json
- src/routes/__tests__/TaskListPage.test.jsx
> Add test for empty gender in payload

- cypress/fixtures/RoRo-Unaccompanied-Trailer-only.json
- cypress/fixtures/target-information.json
- cypress/fixtures/unaccompanied-task-details.json
- cypress/integration/cerberus/issue-a-target.spec.js
- cypress/integration/cerberus/task-version-details.spec.js
Add tests to verify RoRo unaccompanied tasks display Trailer details on task list and TIS
run tests `Should verify task version details of unaccompanied task on task details page` and `Should verify task version details of RoRo-unaccompanied with only trailer task on task details page` from  spec`task-version-details.spec.js`
run tests `Should submit a target successfully from a RoRo-Unaccompanied task and it should be moved to target issued tab` and `Should submit a target successfully from a RoRo-Unaccompanied only with Trailer task and it should be moved to target issued tab` from  spec `issue-a-target.spec.js`
\* Required
> COP-9564: Add tests to verify RoRo unaccompanied tasks display Trailer details on task list and TIS

- src/routes/TaskLists/TaskListMode.jsx
- src/utils/__tests__/genderFormatter.test.jsx
- src/utils/genderFormatter.jsx
This PR pulls out the Gender formatter into it's own util file for better testability
\* Required
> Gender formatter util & test

- cypress/fixtures/RoRo-Tourist-muliple-passengers.json
- cypress/fixtures/RoRo-Tourist-single-passengers.json
- cypress/integration/cerberus/create-tasks.spec.js
- cypress/support/commands.js
Add automation tests to verify the task summary details of different RoRo Tourist task details.
run following tests from spec `create-tasks.spec.js`
`Should create a RoRo task with payload contains multiple passengers`
`Should create a RoRo task with payload contains Single passenger`
`Should verify the RoRo Tourist task with Vehicle Details`
\* Required
> COP-9675: Add tests to verify different RoRO Tourist task details

- cypress/integration/cerberus/task-details.spec.js
> COP-8753 Indicate vessel and vehicle type for tasks in task list (icons)

- cypress/integration/cerberus/task-management.spec.js
- cypress/support/commands.js
Rules, Selector and risk should be displayed in task header in task management
> COP-9704 task header detail

- cypress/fixtures/RoRo-Tourist-NoVehicle.json
- cypress/integration/cerberus/create-tasks.spec.js
- cypress/integration/cerberus/task-details.spec.js
Group icon should be displayed for Tourist without vehicle but has a lead and another passenger
Use existing tasks instead of creating new ones
> Cop 9782 icons in task

- src/routes/TaskDetails/TaskVersions.jsx
- src/utils/roroDataUtil.jsx
…celling targeting issue
Fixed the issue of incrementing the passenger list when can cancelling a targeting issue
1. Claim a task on task management page
2. Check the total number of Occupants
3. Click on Issue Target button
4. Click on cancel button
5. The total number of occupants should be the same
\* Required
> COP-9976: Fixed the issue of incrementing the passenger

- cypress/integration/cerberus/task-details.spec.js
- cypress/support/commands.js
Update test to create a task which has businessKey contains forward slash
run test `Should complete assessment of a task with a reason as take no further action` from spec `task-details.spec.js`
\* Required
> COP-9639: Update test with businessKey contains forward slash

- src/routes/TaskLists/TaskListPage.jsx
- src/routes/__tests__/TaskListPage.test.jsx
COP-9796: Correctly showing counts for selector only selection
Select any selector on task list page and click on button Apply filters. The results would show the correct counts
\* Required
> COP-9796: correctly showing counts for selector only selection

- .drone.yml
> Cpes332 drone

- README.md
- src/routes/TaskLists/TaskListPage.jsx
- src/routes/__fixtures__/taskListData.fixture.json
> Cop 100033 fix threat level in task list

- src/routes/TaskDetails/TaskVersions.jsx
COP-10033: Threat level correctly showing up on task details page
\* Required
> COP-10033: Threat level correctly showing up on task details page

- src/routes/TaskLists/TaskListPage.jsx
- src/routes/__tests__/TaskListPage.test.jsx
- src/routes/__tests__/TaskListPageFilters.test.jsx
COP-9956: Any radio button is selected by default
Scenario 1: Any radio button should be selected by default when user land on task list page
Scenario 2: Apply any combination of filters and selectors and after clicking on Clear all filters link. The Any radio would be selected by default
\* Required
> COP-9956: Any radio button is selected by default

- cypress/fixtures/task-details-versions.json
- cypress/integration/cerberus/task-version-details.spec.js
- cypress/support/commands.js
Update test to check passenger information when click on cancel button from TIS
execute test `Should verify task details on each version retained` from spec `task-version-details.spec.js`
\* Required
> COP-9976: Update test to check passenger information when click on cancel button from TIS

- src/routes/TaskLists/TaskListPage.jsx
- src/routes/__assets__/TaskListPage.scss
This PR moved the rule/selector name to a new line underneath the task title.
- Pull & run aginst dev
- Confirm that the selector/rule name e.g. **`Local ref`** is below the task title.
\* Required
> COP-9964 - Rule selector name

- src/routes/TaskLists/TaskListPage.jsx
Showing highest threat level on task list page for Selectors and Rules
Insert few Selectors and Rules for a particular task. That task on a task list page would show the highest threat rule/selector based on inserted data
\* Required
> COP-10055: Showing highest threat level on task list page

- src/routes/TaskLists/TaskListPage.jsx
- src/routes/__tests__/TaskListPage.test.jsx
Risk statement are showing up with new data
\* Required
> COP-10055: Showing up highest threat level on task list page for each task

- cypress/fixtures/RoRo-Accompanied-Freight.json
- cypress/fixtures/RoRo-Tourist-RBT-SBT.json
- cypress/fixtures/RoRo-Tourist.json
- cypress/fixtures/RoRo-Unaccompanied-Freight.json
- cypress/fixtures/RoRo-task-v1.json
- cypress/fixtures/RoRo-task-v2.json
- cypress/fixtures/RoRo-task-v3.json
- cypress/fixtures/task-version/RoRo-task-v1.json
- cypress/fixtures/task-version/RoRo-task-v2.json
- cypress/fixtures/task-version/RoRo-task-v3.json
- cypress/fixtures/task-version/RoRo-task-v4.json
- cypress/fixtures/tasks.json
Update test payload with groupReference field
run the following tests,
`Should create a task with a payload contains RoRo Tourist from RBT & SBT`
`Should create a task with a payload contains RoRo Unaccompanied Freight from SBT`
task should be created successfully.
\* Required
> COP-10092: Update test payload with groupReference field

- src/routes/TaskLists/TaskListPage.jsx
Fix local reference not showing when group reference is not found.
\* Required
> COP-10092 - Code fix for when no group & local reference missing

- src/routes/TaskDetails/TaskVersionsMode/SelectorMatchesTaskVersion.jsx
- src/routes/TaskLists/TaskListPage.jsx
COP-10055: Rules count showing correctly and cosmetic changes for selector matches fields
\* Required
> COP-10055: Rules count showing correctly and cosmetic changes for selectors matches

- src/__assets__/ReactTabs.scss
- src/routes/TaskDetails/TaskVersionsMode/SelectorMatchesTaskVersion.jsx
- src/routes/__tests__/SelectorMatchesTaskVersion.test.jsx
COP-8641: Fix unique key warning and moved test file into __tests__ folder
\* Required
> COP-8641: Fix unique key warning and moved test file into __tests__

- src/routes/TaskDetails/TaskVersionsMode/SelectorMatchesTaskVersion.jsx
The PR adds missing keys for selector matches
\* Required
> COP-8641 - Adds missing key for selector fields

- package.json
- src/constants.js
- src/routes/TaskDetails/TaskVersionsMode/RoRoAccompaniedMode.jsx
- src/routes/TaskDetails/TaskVersionsMode/RoRoTouristMode.jsx
- src/routes/TaskDetails/TaskVersionsMode/SectionRenderer.jsx
- src/routes/__assets__/TaskDetailsPage.scss
- src/routes/__tests__/TaskDetailsPage.test.jsx
- src/routes/__tests__/TaskVersions.test.jsx
- src/routes/__tests__/TaskVersionsMode/SectionRenderer.test.jsx
- src/utils/formatField.jsx
COP-10127: Driver and occupant details shown as per design
\* Required
> COP-10127: Driver and occupant details shown as per design

- cypress.json
Add cypress.json with basic config
N/A
\* Required
> Add cypress.json with basic config

- cypress/fixtures/has-counts-and-unknown-counts/task-with-occupant-count.json
- cypress/fixtures/has-counts-no-unknown-counts/task-with-occupant-counts-no-unknown.json
- cypress/fixtures/no-counts-has-unknown-counts/task-with-occupant-no-counts-with-unknown-counts.json
- cypress/fixtures/no-counts-vehicle-missing-attributes/task-with-occupant-no-counts-vehicle-missing-attr.json
- cypress/fixtures/task-occupant-count-expected.json
- cypress/integration/cerberus/task-occupant-count.spec.js
- cypress/support/commands.js
Add tests to verify Occupant counts on task details page
run all the tests in the spec task-occupant-count.spec.js``
\* Required
> COP-10007: Add tests to verify Occupant counts on task details page

- cypress/integration/cerberus/task-details.spec.js
- cypress/support/commands.js
Add tests to verify re-listed tag persist across all tabs
run the test `Should complete assessment of a task with a reason as take no further action` from spec `task-details.spec.js`
\* Required
> COP-9861: Add tests to verify re-listed tag persist across all tabs

- src/routes/TaskDetails/TaskVersionsMode/SectionRenderer.jsx
- src/routes/__tests__/TaskVersionsMode/SectionRenderer.test.jsx
Highlighting diff fields between versions
Click on the following URL. The diff fields between versions would be highlighted
http://localhost:8080/tasks/Shakir-Demo-15-02-2022-Selector-different-versions-task_541666:CMID=TEST
\* Required
> COP-10127: Hightlighting diff fields between versions

- src/routes/TaskDetails/TaskVersionsMode/RoRoAccompaniedMode.jsx
- src/routes/TaskDetails/TaskVersionsMode/SectionRenderer.jsx
- src/routes/__tests__/TaskVersionsMode/SectionRenderer.test.jsx
- src/utils/formatField.jsx
Using arrival time for validity label
\* Required
> COP-10127: Using arrival time for validity label

- src/routes/TaskDetails/TaskVersionsMode/RoRoAccompaniedMode.jsx
- src/routes/TaskDetails/TaskVersionsMode/RoRoTouristMode.jsx
- src/routes/TaskDetails/TaskVersionsMode/SectionRenderer.jsx
- src/routes/__tests__/TaskVersionsMode/SectionRenderer.test.jsx
Using ETA to calculate the validity label instead of booking date
\* Required
> COP-10127: Using ETA to calculate the validity label

- src/routes/TaskDetails/TaskVersionsMode/SelectorMatchesTaskVersion.jsx
- src/routes/__fixtures__/taskVersionSelectors.js
- src/routes/__tests__/SelectorMatchesTaskVersion.test.jsx
Warning details are being limited to 500 chars using javascript
\* Required
> COP-9101: handling 500 chars limit at FE

- src/routes/TaskDetails/TaskVersionsMode/SelectorMatchesTaskVersion.jsx
- src/routes/__fixtures__/taskVersionSelectors.js
- src/routes/__tests__/SelectorMatchesTaskVersion.test.jsx
Only apply the the substring to limit to 500 chars when the warning details text is available
\* Required
> COP-9101: Fixed the blank page issue

- src/routes/TaskLists/TaskListPage.jsx
- src/routes/__tests__/TaskListPage.test.jsx
This PR adds the pagination that is located at the bottom of the page when there are multiple tasks to the top of the page underneath the tab title.
- Pull & run against dev.
- **`WHEN`** a tab contains multiple pages, **`THEN`** verify that the pagination menu also shows up at the top of the page.
\* Required
> COP-10254 Page navigation

- src/routes/TaskLists/TaskListPage.jsx
Selector group reference and selector label need to be bold
- view task list
- > the reference should be bold (the line under the businessKey e.g. `Paid by cash`
- > the word `Selector` should be bold when it appears
\* Required
> COP-10256 Add bold tag to selector and selector group ref

- src/routes/TaskDetails/TaskDetailsPage.jsx
- src/routes/__assets__/TaskDetailsPage.scss
- src/routes/__assets__/TaskListPage.scss
- update tag should be orange
- relisted tag should be green
- new tag should be green
- view task list
- find a relisted task
- > relisted tag should be green
- find an updated task
- > updated tag should be orange
- go to task details
- > new tag should be green
\* Required
> COP-10259 Update tag colours

- src/routes/TaskDetails/TaskVersions.jsx
Daylight time saving
Task details page now showing the daylight saving time
http://localhost:8080/tasks/AUTOTEST-28-03-2022-RORO-Tourist-VERSION-DETAILS_616905:CMID=TEST
\* Required
> COP-10439: Daylight time saving

- .drone.yml
- src/routes/TaskDetails/TaskVersionsMode/SelectorMatchesTaskVersion.jsx
> Release 1.6.4

- src/routes/TaskDetails/TaskVersionsMode/EnrichmentCount.jsx
- src/routes/TaskDetails/TaskVersionsMode/SectionRenderer.jsx
- src/routes/__assets__/TaskDetailsPage.scss
- src/routes/__tests__/TaskVersionsMode/EnrichmentCount.test.jsx
- src/routes/__tests__/TaskVersionsMode/SectionRenderer.test.jsx
- src/routes/__tests__/TaskVersionsMode/__snapshots__/SectionRenderer.test.jsx.snap
- src/utils/numberWithCommas.jsx
Aggregated counts for enrichment counts on task details page
http://localhost:8080/tasks/CERB-ROROXML:CMID=194b5ba974ea92e20bbc7c264c9eec99_c3ebe58ab272e75d21923ee4552c7bc15
http://localhost:8080/tasks/CERB-ROROXML:CMID=194b5ba974ea92e20bbc7c264c9eec99_c3ebe58ab272e75d21923ee4552c7bc45
http://localhost:8080/tasks/CERB-ROROXML:CMID=194b5ba974ea92e20bbc7c264c9eec99_c3ebe58ab272e75d21923ee4552c7bc55
\* Required
> COP-10259: Aggregated counts for enrichment counts on task details page

- src/routes/TaskDetails/TaskVersionsMode/EnrichmentCount.jsx
- src/routes/__tests__/TaskVersionsMode/SectionRenderer.test.jsx
- src/routes/__tests__/TaskVersionsMode/__snapshots__/SectionRenderer.test.jsx.snap
Showing - for movement counts undefined
http://localhost:8080/tasks/VER-28-03-2022-RoRo-UNACCOMP-_100958:CMID=TEST
\* Required
> COP-10250: showing hypens for movement counts undefined

- cypress/fixtures/accompanied-task-2-passengers-details.json
- cypress/fixtures/expected-risk-indicators.json
- cypress/fixtures/selectors-group-versions-expected.json
- cypress/fixtures/tasks.json
- cypress/fixtures/tourist-mulitple-versions/RoRo-Tourist-2-passengers-v1.json
- cypress/fixtures/tourist-mulitple-versions/RoRo-Tourist-2-passengers-v2.json
- cypress/fixtures/tourist-mulitple-versions/RoRo-Tourist-2-passengers-v3.json
- cypress/fixtures/tourist-task-details.json
- cypress/fixtures/tourist-task-with-vehicle-details.json
- cypress/fixtures/unaccompanied-task-details.json
- cypress/integration/cerberus/create-tasks.spec.js
- cypress/integration/cerberus/task-details.spec.js
- cypress/integration/cerberus/task-version-details.spec.js
- cypress/support/commands.js
Add all the changes done for tests during 1.6.4 release
Run all the tests.
\* Required
> Release-1.6.4: Cerberus1.6.4 release testing

- src/constants.js
- src/routes/roro/TaskLists/TaskListMode.jsx
- src/utils/__tests__/calculateDatetimeDifference.test.js
- src/utils/calculateDatetimeDifference.js
This PR makes the calculation of time differences generic.
> Cop 10498 generic time diff

- src/routes/airpax/TaskDetails/TaskDetailsPage.jsx
First of two PRs
This one creates the page structure & calls the existing TaskNotes
The next one will refactor tasknotes
Go to http://localhost:8080/airpax/tasks/<taskId>
You should see the title section, a 2/3rds section on the left for version details, and the task activity in 1/3rd column on the right
\* Required
> COP-10427 Add structure

- cypress/integration/cerberus/issue-a-target.spec.js
- cypress/integration/cerberus/task-details.spec.js
- cypress/support/commands.js
Update tests for dismiss and assessment complete tasks.
Also fixed some of the failing tests.
run the following tests from `task-details.spec.js`
`Should dismiss a task with a reason`
`Should dismiss a task with a reason and without notes`
`Should complete assessment of a task with a reason as take no further action`
\* Required
> COP-10257: Update tests for dismiss and assessment complete tasks

- cypress/fixtures/has-counts-and-unknown-counts/task-with-occupant-count.json
- cypress/fixtures/has-counts-no-unknown-counts/task-with-occupant-counts-no-unknown.json
- cypress/fixtures/no-counts-has-unknown-counts/task-with-occupant-no-counts-with-unknown-counts.json
- cypress/fixtures/no-counts-vehicle-missing-attributes/task-with-occupant-no-counts-vehicle-missing-attr.json
- cypress/integration/cerberus/create-tasks.spec.js
- cypress/integration/cerberus/task-booking-date-time-verify.spec.js
- cypress/support/commands.js
Update tests for checking Occupant counts along with enrichment counts
run all the tests from spec `task-occupant-count.spec.js`
\* Required
> COP-10625: Update tests for Occupant counts

- src/routes/airpax/__tests__/TaskVersions.test.jsx
- src/routes/airpax/__tests__/builder/Booking.test.jsx
- src/routes/airpax/__tests__/builder/__snapshots__/Booking.test.jsx.snap
- src/routes/airpax/__tests__/utils/BookingUtil.test.js
- src/routes/airpax/utils/bookingUtil.js
This PR adds tests for the task details booking component
\* Required
> Cop 10438 task details booking tests

- .drone.yml
This PR updates the branch which the `deploy-to-dev` stage in the `drone.yml` file uses.
\* Required
> updates drone.yml to deploy to dev from develop branch

- src/routes/roro/TaskDetails/TaskVersionsMode/SectionRenderer.jsx
- src/routes/roro/__tests__/TaskVersionsMode/SectionRenderer.test.jsx
This PR address a bug found in **STAGING** whereby if we were to receive an invalid country code such as **UN**, the task details page would fail to load.
\* Required
> COP-10719 - Handles blank page load error when country code is invalid

- src/utils/__tests__/roroDataUtil.test.jsx
- src/utils/roroDataUtil.jsx
This PR addresses a missed scenario that needed validation where country code node would be missing entirely.
> COP-10724 - Country code blank page

- src/routes/airpax/TaskDetails/TaskVersions.jsx
- src/routes/airpax/TaskDetails/builder/Booking.jsx
- src/routes/airpax/TaskDetails/builder/CoTraveller.jsx
- src/routes/airpax/TaskDetails/builder/Document.jsx
- src/routes/airpax/TaskDetails/builder/Passenger.jsx
- src/routes/airpax/TaskDetails/builder/Voyage.jsx
- src/routes/airpax/__assets__/TaskDetailsPage.scss
- src/routes/airpax/__tests__/TaskVersions.test.jsx
- src/routes/airpax/__tests__/__snapshots__/TaskVersions.test.jsx.snap
- src/routes/airpax/__tests__/builder/CoTraveller.test.jsx
- src/routes/airpax/__tests__/builder/__snapshots__/Booking.test.jsx.snap
- src/routes/airpax/__tests__/builder/__snapshots__/Document.test.jsx.snap
This PR adds test for the co traveller section on the air pax task details.
> Note: This PR also brings minor consistency to jsx styling across the components used on the task details page.
\* Required
> COP-10463 - Test & Code refactor

- src/routes/airpax/TaskDetails/builder/SelectorMatches.jsx
- src/routes/airpax/TaskLists/TaskListSectionBuilder.jsx
- src/routes/airpax/__tests__/utils/RisksUtil.test.js
- src/routes/airpax/__tests__/utils/__snapshots__/RisksUtil.test.js.snap
- src/routes/airpax/utils/index.js
- src/routes/airpax/utils/risksUtil.jsx
This PR simply changes the `indicatorUtils` name to `risksUtil`.
\* Required
> Renames indicatorsUtils to risksUtils

- src/constants.js
- src/utils/Form/cleanSubmission.js
- src/utils/Form/cleanSubmission.test.js
- src/utils/Form/formHooks.js
- src/utils/Form/formHooks.test.js
- src/utils/Form/generateBusinessKey.js
- src/utils/Form/generateBusinessKey.test.js
- src/utils/Form/getProcessInstance.js
- src/utils/Form/getProcessInstance.test.js
- src/utils/Form/getRenderer.js
- src/utils/Form/getRenderer.test.js
- src/utils/Form/getSubmissionPayload.js
- src/utils/Form/getSubmissionPayload.test.js
- src/utils/Form/index.js
- src/utils/Form/setupSubmission.js
- src/utils/Form/setupSubmission.test.js
Added utility functions, ported from [cop-ui](https://github.com/UKHomeOffice/cop-ui), for handling the output from the COP React Form Renderer.
https://support.cop.homeoffice.gov.uk/browse/COP-10641
(also https://support.cop.homeoffice.gov.uk/browse/COP-10219)
Covered by accompanying unit tests, also ported from [cop-ui](https://github.com/UKHomeOffice/cop-ui).
\* Required
> COP-10641: Add Form utilities

- .drone.yml
> removes branch condition that were left in drone.yml by accident

- src/routes/airpax/TaskLists/TasksTab.jsx
- src/routes/airpax/__tests__/TaskListPage.test.jsx
This PR updates the filter parameters for fetching tasks on the different tabs on task list page.
> updates task list filter params

- src/components/ClaimUnclaimTask.jsx
- src/components/__tests__/ClaimUnclaimTask.test.jsx
- src/constants.js
- src/routes/airpax/TaskLists/TaskListCard.jsx
- src/routes/airpax/TaskLists/TaskListPage.jsx
- src/routes/airpax/TaskLists/TasksTab.jsx
- src/routes/airpax/__fixtures__/targetListData.js
- src/routes/airpax/__fixtures__/taskData_AirPax_AssigneeCurrentUser.fixture.json
- src/routes/airpax/__fixtures__/taskData_AirPax_AssigneeOtherUser.fixture.json
- src/routes/airpax/__fixtures__/taskData_AirPax_NoAssignee.fixture.json
- src/routes/airpax/__fixtures__/taskData_AirPax_TargetIssued.fixtures.json
- src/routes/airpax/__fixtures__/taskData_AirPax_TaskComplete.fixture.json
- src/routes/airpax/__fixtures__/taskData_AirPax_TaskDetails.fixture.json
- src/routes/airpax/__tests__/TaskListPage.test.jsx
- src/routes/airpax/__tests__/__snapshots__/TaskVersions.test.jsx.snap
- src/routes/airpax/__tests__/builder/Itinerary.test.jsx
- src/routes/airpax/__tests__/builder/Passenger.test.jsx
- src/routes/airpax/__tests__/builder/__snapshots__/Itinerary.test.jsx.snap
- src/routes/airpax/__tests__/utils/BookingUtil.test.js
- src/routes/airpax/__tests__/utils/DateTimeUtil.test.js
- src/routes/airpax/__tests__/utils/MovementUtil.test.js
- src/routes/airpax/__tests__/utils/__snapshots__/MovementUtil.test.js.snap
- src/routes/airpax/utils/datetimeUtil.js
- src/routes/airpax/utils/movementUtil.jsx
Wire up the claim/ unclaim button
Run it locally
http://localhost:3000/airpax/tasks
Task list page:
Task details page:
\* Required
> COP-10847: Wire up the claim/ unclaim button

- src/routes/airpax/TaskDetails/builder/Passenger.jsx
- src/routes/airpax/__tests__/__snapshots__/TaskVersions.test.jsx.snap
- src/routes/airpax/__tests__/builder/Passenger.test.jsx
- src/routes/airpax/__tests__/utils/PersonUtil.test.js
- src/routes/airpax/utils/personUtil.jsx
This PR is a minor cosmetic touch up on the `Passenger` section on task details page.
> COP-10436 - Refactor passenger task details

- src/routes/airpax/TaskDetails/builder/Document.jsx
- src/routes/airpax/TaskLists/TaskListSectionBuilder.jsx
- src/routes/airpax/__tests__/__snapshots__/TaskVersions.test.jsx.snap
- src/routes/airpax/__tests__/builder/__snapshots__/Booking.test.jsx.snap
- src/routes/airpax/__tests__/builder/__snapshots__/Document.test.jsx.snap
- src/routes/airpax/__tests__/utils/DateTimeUtil.test.js
- src/routes/airpax/__tests__/utils/DocumentUtil.test.js
- src/routes/airpax/utils/datetimeUtil.js
- src/routes/airpax/utils/documentUtil.js
This PR is a minor cosmetic touch up on the `Document` section on task details page.
> COP-10437 - Refactor document task details

- src/routes/airpax/__tests__/builder/__snapshots__/Itinerary.test.jsx.snap
- src/routes/airpax/__tests__/utils/MovementUtil.test.js
- src/routes/airpax/utils/movementUtil.jsx
This PR is a minor cosmetic touch up on the `Itinerary` section on task details page.
> COP-10462 - Refactor Itinerary task details

- src/routes/airpax/__assets__/TaskListPage.scss
- src/routes/airpax/__tests__/utils/__snapshots__/MovementUtil.test.js.snap
- src/routes/airpax/utils/movementUtil.jsx
This small PR is a cosmetic fix up of how the letters within the label is displayed & updates the colours used (overrides the default applied by `hods-tag` styling).
> COP-10838 - Refactors the movement departure movement status

- src/routes/airpax/TaskDetails/TaskVersions.jsx
- src/routes/airpax/TaskDetails/builder/CoTraveller.jsx
- src/routes/airpax/__assets__/TaskDetailsPage.scss
- src/routes/airpax/__tests__/__snapshots__/TaskVersions.test.jsx.snap
This PR is a minor cosmetic touch up on the `Co-Travellers` section on task details page.
> COP-10463 - Refactor co-traveller task details

- src/routes/access/PnrAccessRequest.jsx
This PNR just adds the user selection to the post body when user submits a request to either say they want to view PNR data or not.
> COP-10872 - Adds user selection to the pnr post request

- src/cop-forms/viewPnrData.js
- src/routes/airpax/TaskLists/TaskListCard.jsx
- src/routes/airpax/TaskLists/TaskListSectionBuilder.jsx
- src/routes/airpax/__assets__/TaskDetailsPage.scss
- src/routes/airpax/__tests__/TaskListCard.test.jsx
This PR simply adds the task title to each task on the task list.
- Pull & run against `cop-targeting-api` dev
- Verify that each task card is rendered with a task title (similar to the screenshot below)
> COP-10887 - Adds the task title

- cypress/fixtures/airpax/airpax-task-expected-details.json
- cypress/fixtures/airpax/task-airpax.json
- cypress/integration/airpax/airpax-task-details.spec.js
- cypress/support/commands.js
Add automation tests for verifying document section of airpax task
run the test from spec `airpax-task-details.spec.js`
\* Required
> COP-10437: Add automation tests for verifying document section of airpax task

- package-lock.json
- package.json
Adds githooks to this repo.
This ensures that we do not push code which has linting errors / failing unit tests.
> COP-10884 - Adds githooks

- cypress/fixtures/airpax/airpax-expected-response.json
- cypress/fixtures/airpax/task-airpax.json
- cypress/integration/airpax/airpax-task-details.spec.js
- cypress/integration/airpax/create-aipax-tasks.spec.js
- cypress/integration/airpax/task-list-page.spec.js
- cypress/support/commands.js
Update airPax tests to accept PNR terms after login
run all the tests inside folder `cypress/integration/airpax`
\* Required
> COP-10872: Update airPax tests to accept PNR terms after login

- src/routes/airpax/TaskDetails/TaskDetailsPage.jsx
- src/routes/airpax/__fixtures__/taskData_AirPax_ClaimedTask.fixture.json
- src/routes/airpax/__tests__/TaskDetailsPage.test.jsx
Display action buttons on task details page for a claimed task
\* Required
> COP-10868: Display action button on task details page

- cypress/integration/airpax/task-list-page.spec.js
COP-10845: Verify this endpoint /v2/targeting-tasks/pages will return an Internal 500 server error
\* Required
> COP-10845_Validate /v2/targeting-tasks/pages does not return 500 error

- cypress/integration/airpax/airpax-task-details.spec.js
Added script for COP-10877 Display Task notes
\* Required
> COP-10877 Display Task notes

- src/routes/airpax/TaskDetails/TaskDetailsPage.jsx
- src/routes/airpax/__tests__/TaskDetailsPage.test.jsx
- src/routes/roro/__assets__/TaskDetailsPage.scss
This PR simple adds the new label to a new task that is unclaimed.
> Scenarios to test:
- For a task that is claimed (state is now **IN PROGRESS**), it **SHOULD NOT** display the **`NEW`** label in task details page.
- For a new task that is unclaimed, it **SHOULD** display the **`NEW`** label in task details page.
- For a task that is in **`ISSUED`** state, it **SHOULD NOT** display the **`NEW`** label in task details page.
- For a task that is in **`COMPLETE`** state, it **SHOULD NOT** display the **`NEW`** label in task details page.
> COP-10912 - Task details page new label

- src/constants.js
This adds missing post parameter entries for fetching status counts.
\* Required
> COP-10536 - Adds missing entry to post params

- cypress/fixtures/airpax/taskSummaryExpected.json
- cypress/integration/airpax/airpax-task-overview-page.spec.js
- cypress/support/commands.js
Add tests to verify task summary details for airPax task
execute test  from spec `airpax-task-overview-page.spec.jsn`
`Should check AirPax task information on task overview`
\* Required
> COP-10222: Add tests to verify task summary details for airPax task

- cypress/integration/airpax/task-list-page.spec.js
- cypress/integration/cerberus/filter-tasks-by-pre-arrival-mode.spec.js
COP-10536 Implement mode filter
https://support.cop.homeoffice.gov.uk/browse/COP-10536
Run  filter-tasks-by-pre-arrival-mode.spec.js 
"Should verify filter by mode and Link to AirPax is displayed"
Run airpax/task-list-page.spec.js
"Should verify filter by mode and Link to Roro is displayed"
\* Required
> COP-10536 First Commit

- src/constants.js
- src/routes/airpax/TaskLists/TaskListSectionBuilder.jsx
- src/routes/airpax/__assets__/TaskDetailsPage.scss
- src/routes/airpax/__tests__/utils/MovementUtil.test.js
- src/routes/airpax/utils/movementUtil.jsx
This PR adds the **`RELIST`** label to a target task if it has been relisted.
> COP-10954 - Adds relist label

- src/constants.js
- src/routes/airpax/TaskLists/TaskListSectionBuilder.jsx
- src/routes/airpax/__assets__/TaskDetailsPage.scss
- src/routes/airpax/__tests__/utils/MovementUtil.test.js
- src/routes/airpax/utils/movementUtil.jsx
This PR adds the **`UPDATED`** label to a task with multiple versions/ or the `latestVersionNumber` is greater than 1
> COP-10953 - Adds updated label

- cypress/integration/airpax/filter-airpax-tasks-by-selectors.spec.js
- cypress/support/commands.js
Implement Selectors filter
https://support.cop.homeoffice.gov.uk/browse/COP-10849
Run filter-airpax-tasks-by-selectors.spec.js
\* Required
> COP-10849 : Implement Selectors filter

- cypress/fixtures/airpax/task-airpax-no-rules-selectors.json
- cypress/integration/airpax/airpax-task-details.spec.js
Add tests to check No rules & selectors in a task
run test `Should verify No selectors & rules on task details page` from spec `airpax-task-details.spec.js`
\* Required
> COP-10891: Add tests to check No rules & selectors in a task

- src/routes/airpax/TaskDetails/builder/Passenger.jsx
- src/routes/airpax/TaskLists/TasksTab.jsx
- src/routes/airpax/__tests__/builder/Passenger.test.jsx
- src/routes/airpax/__tests__/utils/PersonUtil.test.js
- src/routes/airpax/utils/personUtil.jsx
This PR corrects the previously implemented age at travel logic.
> ### Supplemental
- This PR also fixes pagination between pages
> COP-10436 - Corrects age at travel logic

- src/routes/roro/TaskLists/TaskListPage.jsx
This PR fixes a bug introduced which broke roro status-counts fetch.
> COP-10960 - Status counts (RoRo)

- cypress/fixtures/airpax/task-airpax-Crew.json
- cypress/fixtures/airpax/taskSummaryExpected-Crew.json
- cypress/integration/airpax/airpax-task-overview-page.spec.js
- cypress/support/commands.js
Add tests to verify task with Crew members
run the test `Should verify task summary displays Crew` from spec `airpax-task-overview-page.spec.js`
\* Required
> COP-10939: Add tests to verify task with Crew members

- src/routes/airpax/TaskLists/TaskListPage.jsx
This PR fixes a bug introduced which broke some of airpax status-counts post params.
> COP-10960 - Airpax status params

- src/__assets__/ReactTabs.scss
- src/routes/airpax/__tests__/utils/RisksUtil.test.js
- src/routes/airpax/utils/risksUtil.jsx
Remove mappings for warning code at the frontend for Airpax and rendering what is being returned from the backend
\* Required
> Removed warning mapping at Frontend

- src/routes/airpax/TaskLists/TaskListSectionBuilder.jsx
- src/routes/airpax/__tests__/utils/RisksUtil.test.js
- src/routes/airpax/utils/risksUtil.jsx
> add highestThreatLevel to airpax task list

- cypress/fixtures/airpax/airpax-task-expected-details.json
- cypress/fixtures/airpax/task-airpax-rules-selectros-with-diff-threat-category.json
- cypress/fixtures/airpax/task-airpax-rules-with-diff-threat.json
- cypress/integration/airpax/airpax-task-details.spec.js
- cypress/integration/airpax/create-aipax-tasks.spec.js
- cypress/support/commands.js
Add tests to verify Booking details of AirPax task
run test from spec `airpax-task-details.spec.js` 
`Should verify Booking details of an AirPax task on task details page`
\* Required
> COP-10438: Add tests to verify Booking details of AirPax task

- src/routes/airpax/__tests__/utils/RisksUtil.test.js
- src/routes/airpax/utils/risksUtil.jsx
> Adds fix to match highestThreatLevel to selectors/rules

- src/__assets__/_utilities.scss
- src/routes/airpax/TaskDetails/TaskSummary.jsx
- src/routes/airpax/TaskDetails/TaskVersions.jsx
- src/routes/airpax/__fixtures__/taskSummaryAirPaxData.fixture.json
- src/routes/airpax/__tests__/TaskSummary.test.jsx
- src/routes/airpax/__tests__/__snapshots__/TaskVersions.test.jsx.snap
- src/routes/airpax/__tests__/utils/MovementUtil.test.js
- src/routes/airpax/utils/movementUtil.jsx
- src/utils/__tests__/calculateDatetimeDifference.test.js
- src/utils/calculateDatetimeDifference.js
Added summary of the flight/passenger details at the top of task
\* Required
> COP-10459: showing flight summary at the top of task

- cypress/fixtures/airpax/task-airpax-rules-with-diff-rule-id.json
- cypress/integration/airpax/airpax-task-details.spec.js
- cypress/integration/airpax/filter-airpax-tasks-by-ruleID.spec.js
- cypress/support/commands.js
Add tests to verify filter tasks by rule ID
run tests from spec `filter-airpax-tasks-by-ruleID.spec.js`
\* Required
> COP-10851: Add tests to verify filter tasks by rule ID

- cypress/integration/airpax/airpax-task-details.spec.js
Add tests to verify the task version structure
run test from spec `airpax-task-details.spec.js`
`Should verify tasks are generated with more than one version`
\* Required
> COP-10471: Add tests to verify the task version structure

- src/routes/airpax/TaskDetails/TaskSummary.jsx
- src/routes/airpax/TaskLists/TaskListSectionBuilder.jsx
- src/routes/airpax/__assets__/TaskListPage.scss
- src/routes/airpax/__tests__/TaskListCard.test.jsx
- src/routes/airpax/__tests__/TaskListPage.test.jsx
- src/routes/airpax/__tests__/TaskSummary.test.jsx
- src/routes/airpax/__tests__/__snapshots__/TaskVersions.test.jsx.snap
- src/routes/airpax/__tests__/utils/DateTimeUtil.test.js
- src/routes/airpax/__tests__/utils/MovementUtil.test.js
- src/routes/airpax/utils/datetimeUtil.js
- src/routes/airpax/utils/movementUtil.jsx
- src/utils/__tests__/calculateDatetimeDifference.test.js
- src/utils/calculateDatetimeDifference.js
This PR fixes bug on airpax task list page as swell as refactors existing tests while adding a few more due to the change.
> COP-10991 - Fixes relative time bug on airpax task list bug

- webpack.config.js
There was an issue with the local proxy set up where the origin header wasn't being replaced properly. This caused CORS issues when using the dev task API.
\* Required
> Fixed a CORS issue when using local to proxy to the dev task API

- cypress/fixtures/airpax/dismiss-task-airpax.json
- cypress/fixtures/airpax/issue-task-airpax.json
- cypress/integration/airpax/airpax-task-overview-page.spec.js
- cypress/support/commands.js
Add test to verify tasks overview page of a task from each tab loads successfully.
npm run cypress:test:local -- --spec cypress/integration/airpax/airpax-tasks-overview-page.spec.js
Should verify task overview page for a task from each tab loads successfully
\* Required
> COP-10942 : Add test to verify tasks overview page of a task from each tab loads successfully.

- src/routes/airpax/TaskDetails/TaskVersions.jsx
- src/routes/airpax/__tests__/TaskVersions.test.jsx
- src/routes/airpax/__tests__/__snapshots__/TaskVersions.test.jsx.snap
fixed a typo in PNR API url
\* Required
> COP-10472: fixed a typo in PNR API url

- cypress/fixtures/airpax/task-airpax-selectors-selector-matched-rule.json
- cypress/fixtures/task-roro-selectors-selector-matched-rule.json
- cypress/integration/airpax/airpax-task-details.spec.js
- cypress/integration/cerberus/task-details.spec.js
Add tests for checking highest threat level with Selectors & rules
Add test to check rule with name "Selector Matched Rule" is not displayed.
"When there is a selector match, then a rule match is also generated. 
This rule match should not be displayed or included in any rule counts"
run the following tests
`Should verify Matched Rules with rule name Selector Matched Rule not visible on task details page`
`Should verify Matched Rules with rule name Selector Matched Rule not visible on task details page`
`Should check rule matches details on task details page`
`Should check  rule matches details for more than one version on task management page`
\* Required
> [COP-10952, COP-10746 ] Add tests for checking highest threat level with Selectors & rules

- src/cop-forms/completeTaskCerberus.js
This PR removes an unwanted label for the task completion form.
> Removeds unwanted label on task completion form

- src/routes/roro/TaskDetails/TaskDetailsPage.jsx
Also support autofilling sex for co-travellers
\* Required
> COP-10741: Autofill co-traveller gender

- cypress/integration/airpax/airpax-task-overview-page.spec.js
Add test verify Notes are shown after correcting a validation error
npm run cypress:test -- --spec cypress/integration/cerberus/airpax-tasks-overview-page.spec.js
\* Required
> COP-10892 : Add test verify Notes are shown after correcting a validation error

- cypress/fixtures/airpax/airpax-TIS-details.json
- cypress/integration/airpax/airpax-task-details.spec.js
- cypress/integration/airpax/airpax-task-overview-page.spec.js
- cypress/support/commands.js
Add test to verify a Complete task
npm run cypress:test:local -- --spec cypress/integration/airpax/airpax-task-overview-page.spec.js
Should complete a task and validate it is moved to the Complete tab
\* Required
> COP-10475 : Add test for Complete task

- src/routes/airpax/utils/targetInformationUtil.js
Adds handling for invalid outputs when constructing the tis submission data.
> COP-11198 - Adds missing handling for invalid values

- src/components/Filter.jsx
- src/constants.js
- src/cop-forms/filter.js
- src/routes/airpax/TaskLists/TaskListPage.jsx
https://support.cop.homeoffice.gov.uk/browse/COP-11014
A search box has been placed on the airpax task page and can be used to search by task Id or by passenger names.
Use the search box and verify that the counts and results are correct
\* Required
> COP-11014 Added a search box for Airpax tasks

- src/config.js
[COP-11272](https://support.cop.homeoffice.gov.uk/browse/COP-11272) fix feature toggle for cop targeting api
\* Required
> handles env var as a string into boolean correctly

- .drone.yml
> Fix feature toggle env var

- src/routes/roro/TaskDetails/TaskVersionsMode/SectionRenderer.jsx
- src/routes/roro/__tests__/TaskVersionsMode/SectionRenderer.test.jsx
- src/routes/roro/__tests__/TaskVersionsMode/__snapshots__/SectionRenderer.test.jsx.snap
This PR fixes a bug on occupants count where an update has been received.
- Load up this task https://www.dev.cerberus.cop.homeoffice.gov.uk/tasks/DEV-20220721-1472
- Observe the occupant counts between the 3 versions.
- Between the updates, `NaN` should not be rendered when the counts have been updated.
> COP-10472 - Occupant counts (on update)

- README.md
- cypress/fixtures/airpax/airpax-TIS-details.json
- cypress/fixtures/airpax/airpax-task-expected-details.json
- cypress/fixtures/airpax/taskSummaryExpected-Crew.json
- cypress/fixtures/airpax/taskSummaryExpected.json
- cypress/integration/airpax/airpax-task-details.spec.js
- cypress/integration/airpax/airpax-task-overview-page.spec.js
- cypress/integration/airpax/filter-airpax-tasks-by-selectors.spec.js
- cypress/integration/airpax/task-list-page.spec.js
- cypress/support/commands.js
Added some changes for Air-pax regression test
\* Required
> Applied some fixes for Airpax-regression

- src/components/RenderForm.jsx
- src/components/TaskNotes.jsx
- src/components/__tests__/RenderForm.test.jsx
- src/components/__tests__/TaskNotes.test.jsx
- src/routes/airpax/TaskDetails/TaskDetailsPage.jsx
- src/routes/airpax/__tests__/TaskDetailsPage.test.jsx
- src/routes/roro/TaskDetails/TaskDetailsPage.jsx
- src/routes/roro/__tests__/TaskDetailsPage.test.jsx
This PR moves the error summary to the parent component, in this case `TaskDetailsPage.jsx` for RoRo & AirPax, rather than child components also containing error components which can result in situations where two error summaries are rendered with both error summaries being about the same root cause.
> COP-11413 - Error summary refactor

- cypress/fixtures/airpax/airpax-TIS-details.json
- cypress/fixtures/airpax/task-airpax-latest.json
- cypress/fixtures/airpax/task-airpax-multiple-passengers.json
- cypress/fixtures/airpax/task-airpax-no-rules-selectors.json
- cypress/fixtures/airpax/task-airpax-no-selectors.json
- cypress/fixtures/airpax/task-airpax-rules-selectros-with-diff-threat-category.json
- cypress/fixtures/airpax/task-airpax-rules-v2.json
- cypress/fixtures/airpax/task-airpax-rules-with-diff-rule-id.json
- cypress/fixtures/airpax/task-airpax-selectors-selector-matched-rule.json
- cypress/fixtures/airpax/task-airpax-singlePassenger.json
- cypress/fixtures/airpax/task-airpax.json
- cypress/integration/airpax/airpax-task-details.spec.js
- cypress/integration/airpax/filter-airpax-tasks-by-selectors.spec.js
- cypress/integration/airpax/issue-aipax-tasks.spec.js
Added new data to request payloads for airpax and applied code refactoring to airpax-task-details.spec.js
\* Required
> Added - targetIndicator to Request payloads

- package-lock.json
- package.json
- src/routes/airpax/TaskDetails/TaskDetailsPage.jsx
- src/routes/airpax/utils/targetInformationUtil.js
This PR updates the version number for the form renderer which has had a feature update which now renders an entry point to an empty collection where as before, if a collection was empty, it wasn't rendered.
- Claim a task
- Click on `Issue target`
- The `other passenger details` &  `Checks completed on nominals` sections are collections. You should now be able to see an option on the CYA screen to go to the page and add or remove items and be able to go back to the CYA screen and still have the entry point  option to manipulate the collection.
> COP-11361 - TIS Collection component

- package-lock.json
- package.json
- src/components/Filter.jsx
- src/constants.js
- src/cop-forms/filter.js
- src/routes/roro/TaskLists/Filter.jsx
- src/routes/roro/TaskLists/TaskListPage.jsx
- src/routes/roro/TaskLists/TasksTab.jsx
- src/routes/roro/__tests__/TaskListPage.test.jsx
- src/routes/roro/__tests__/TaskListPageFilters.test.jsx
This PR reverts the RoRo Mode filters to checkboxes for the mode and radio buttons for the selectors.
> COP-11440 - Revert roro mode filter

- src/routes/roro/TaskLists/TasksTab.jsx
Adds missing line of code for movement modes on fetching tasks.
> COP-11440 - Pages endpoint movement modes

- cypress/fixtures/RoRo-Accompanied-Freight_ROROTSV.json
- cypress/fixtures/accompanied-task-details.json
- cypress/fixtures/task-occupant-count-expected.json
- cypress/fixtures/tourist-task-co-travellers.json
- cypress/integration/cerberus/create-tasks.spec.js
- cypress/integration/cerberus/filter-tasks-by-selectors.spec.js
- cypress/integration/cerberus/task-occupant-count.spec.js
- cypress/integration/cerberus/task-version-details.spec.js
- cypress/support/commands.js
ogCOP-11293Added test for SMEs require ability to batch move tasks to completed tab
npm run cypress:test:local -- --spec cypress/integration/cerberus/tasks-version-details.spec.js
\* Required
> COP-11293: Added test for SMEs require ability to batch move tasks to completed tab

- src/components/__tests__/RenderForm.test.jsx
- src/cop-forms/airpaxTisCerberus.js
- src/routes/airpax/TaskDetails/TaskDetailsPage.jsx
- src/routes/airpax/__tests__/TaskDetailsPage.test.jsx
> adds the cerberus airpax tis form config

- kube/deployment.yml
Adds `/files` to the end of the File Upload Service URL
> Add /files to the end of the File Upload Service URL

- cypress/fixtures/airpax/airpax-TIS-details.json
- cypress/fixtures/task-details-versions.json
- cypress/fixtures/tourist-task-with-vehicle-details.json
- cypress/integration/airpax/issue-aipax-tasks.spec.js
- cypress/integration/cerberus/filter-tasks-by-pre-arrival-mode.spec.js
- cypress/integration/cerberus/task-details-vehicle-vessel-icons.spec.js
- cypress/integration/cerberus/task-details.spec.js
- cypress/integration/cerberus/task-management.spec.js
- cypress/integration/cerberus/task-version-details.spec.js
- cypress/support/commands.js
- cypress_mochawesome_report.js
- scripts/run-tests.sh
Add test for Issue target - Journey Direction and Code refactor for Pre-Arrival mode change
npm run cypress:test:local -- --spec cypress/integration/airpax/issue-aipax-tasks.spec.js
Should verify Inbound or Outbound Details in Target Information sheet
\* Required
> COP-11460: Add test for Issue target - Journey Direction and Code refactor for Pre-Arrival mode filter change

- src/utils/Form/getSubmissionPayload.js
- src/utils/Form/getSubmissionPayload.test.js
- src/utils/Form/setupSubmission.test.js
This PR adds the correct businessKey/task ID to the form submission mechanism.
- Claim a task
- Fill out a form, append an image to the main person
- Open the network tab
- Submit the form
- Observe the URL which uploads the photograph, part of the URL will match the task ID
> COP-11519 - Adds correct business key

- src/routes/airpax/TaskDetails/builder/Booking.jsx
- src/routes/airpax/TaskDetails/builder/Document.jsx
- src/routes/airpax/__tests__/__snapshots__/TaskVersions.test.jsx.snap
- src/routes/airpax/__tests__/builder/__snapshots__/Document.test.jsx.snap
- src/routes/airpax/__tests__/builder/__snapshots__/Itinerary.test.jsx.snap
- src/routes/airpax/__tests__/utils/BookingUtil.test.js
- src/routes/airpax/__tests__/utils/DocumentUtil.test.js
- src/routes/airpax/__tests__/utils/MovementUtil.test.js
- src/routes/airpax/__tests__/utils/common.test.js
- src/routes/airpax/utils/bookingUtil.jsx
- src/routes/airpax/utils/common.js
- src/routes/airpax/utils/documentUtil.js
- src/routes/airpax/utils/movementUtil.jsx
- src/routes/airpax/utils/personUtil.jsx
This PR changes all rendered iso2 country codes to iso3 country codes.
e.g.
```
GB -> GBR
FR -> FRA
DE -> DEU
```
This PR also fixes a layout discrepancy on task details page between Document & Baggage section (divider added).
> COP-11527 - iso2 codes to iso3 codes

- cypress/fixtures/task-occupant-count-expected.json
- cypress/integration/cerberus/task-occupant-count.spec.js
- cypress/support/commands.js
Added test for Occupant count fix
\* Required
> COP-11442: Added test for Occupant count fix

- cypress/integration/airpax/issue-aipax-tasks.spec.js
- cypress/integration/cerberus/issue-a-target.spec.js
Added test for Actions "issue Target, Assessment Complete and Dismiss" should not be shown when we have selected an action
\* Required
> COP-11453: Added test for Actions "issue Target, Assessment Complete and Dismiss" should not be shown when we have selected an action

- src/components/Tabs.jsx
- src/routes/airpax/TaskDetails/TaskVersions.jsx
- src/routes/airpax/__tests__/TaskDetailsPage.test.jsx
- src/routes/airpax/__tests__/TaskVersions.test.jsx
- src/routes/airpax/__tests__/__snapshots__/TaskVersions.test.jsx.snap
Remove PNR data tab on task details page
Task details page won't show PNR data tab in version accordion.
\* Required
- [] All reviewer comments resolved/answered? \*
> COP-11638: remove pnr data tab on task details page

- src/routes/airpax/TaskLists/TaskListPage.jsx
Keeping assign to me functionality intact even after the page load
\* Required
> COP-11439: keeping assign to me functionality intact even after the page load

- cypress/integration/airpax/filter-airpax-tasks-by-assignedToMe.spec.js
- cypress/support/commands.js
Added test for "Assigned to me" filter in task list page
npm run cypress:test:local -- --spec cypress/integration/airpax/filter-airpax-tasks-by-assignedToMe.js
Should filter tasks in progress by Assigned to me
\* Required
> COP-11439: Added test for "Assigned to me" filter in task list page

- src/__assets__/_formbuilder-overrides.scss
- src/__assets__/index.scss
Fix TIS form layout
Click the claim button either on tasklist or taskdetails page (Roro journey) to load the form from formbuilder
\* Required
> COP-9874: CSS overrides to fix TIS form layout

- src/routes/airpax/TaskDetails/builder/Booking.jsx
- src/routes/airpax/__fixtures__/targetListData.js
- src/routes/airpax/__fixtures__/taskData_AirPax_AssigneeCurrentUser.fixture.json
- src/routes/airpax/__fixtures__/taskData_AirPax_AssigneeOtherUser.fixture.json
- src/routes/airpax/__fixtures__/taskData_AirPax_ClaimedTask.fixture.json
- src/routes/airpax/__fixtures__/taskData_AirPax_DismissedTask.json
- src/routes/airpax/__fixtures__/taskData_AirPax_NoAssignee.fixture.json
- src/routes/airpax/__fixtures__/taskData_AirPax_TargetIssued.fixtures.json
- src/routes/airpax/__fixtures__/taskData_AirPax_TaskComplete.fixture.json
- src/routes/airpax/__fixtures__/taskData_AirPax_TaskDetails.fixture.json
- src/routes/airpax/__fixtures__/taskData_AirPax_TaskDetails_Selectors.fixture.json
- src/routes/airpax/__fixtures__/taskData_AirPax_TaskDetails_Versions.fixture.json
- src/routes/airpax/__fixtures__/taskData_AirPax_TaskDetails_Versions_PNRData.fixture.json
- src/routes/airpax/__fixtures__/taskSummaryAirPaxData.fixture.json
- src/routes/airpax/__tests__/__snapshots__/TaskVersions.test.jsx.snap
- src/routes/airpax/__tests__/builder/__snapshots__/Booking.test.jsx.snap
- src/routes/airpax/__tests__/utils/BookingUtil.test.js
- src/routes/airpax/__tests__/utils/MovementUtil.test.js
- src/routes/airpax/__tests__/utils/PersonUtil.test.js
- src/routes/airpax/utils/bookingUtil.jsx
- src/routes/airpax/utils/personUtil.jsx
This PR adapts the booking types & numbers functions to handling an array of object nodes.
> COP-11822 - Booking Types & Numbers

- src/routes/airpax/TaskDetails/builder/Booking.jsx
- src/routes/airpax/__fixtures__/targetListData.js
- src/routes/airpax/__fixtures__/taskData_AirPax_AssigneeCurrentUser.fixture.json
- src/routes/airpax/__fixtures__/taskData_AirPax_AssigneeOtherUser.fixture.json
- src/routes/airpax/__fixtures__/taskData_AirPax_ClaimedTask.fixture.json
- src/routes/airpax/__fixtures__/taskData_AirPax_DismissedTask.json
- src/routes/airpax/__fixtures__/taskData_AirPax_NoAssignee.fixture.json
- src/routes/airpax/__fixtures__/taskData_AirPax_TargetIssued.fixtures.json
- src/routes/airpax/__fixtures__/taskData_AirPax_TaskComplete.fixture.json
- src/routes/airpax/__fixtures__/taskData_AirPax_TaskDetails.fixture.json
- src/routes/airpax/__fixtures__/taskData_AirPax_TaskDetails_Selectors.fixture.json
- src/routes/airpax/__fixtures__/taskData_AirPax_TaskDetails_Versions.fixture.json
- src/routes/airpax/__fixtures__/taskData_AirPax_TaskDetails_Versions_PNRData.fixture.json
- src/routes/airpax/__fixtures__/taskSummaryAirPaxData.fixture.json
- src/routes/airpax/__tests__/__snapshots__/TaskVersions.test.jsx.snap
- src/routes/airpax/__tests__/builder/__snapshots__/Booking.test.jsx.snap
- src/routes/airpax/__tests__/utils/BookingUtil.test.js
- src/routes/airpax/__tests__/utils/MovementUtil.test.js
- src/routes/airpax/__tests__/utils/PersonUtil.test.js
- src/routes/airpax/utils/bookingUtil.jsx
- src/routes/airpax/utils/personUtil.jsx
Reverts UKHomeOffice/cerberus-service#810
> Revert "COP-11822 - Booking Types & Numbers"

- src/__assets__/_utilities.scss
Reverting the tickets that got rolled back by deploying the latest release-candidate to DEV
\* Required
> COP-11439: latest release-candidate

- package-lock.json
- package.json
This PR updates the `axios` dependency.
> Updates the axios dependency

- package-lock.json
- package.json
This PR updates the `dayjs` dependency.
> Updates the dayjs dependency

- package-lock.json
- package.json
This PR updates the `formiojs` dependency.
> Updates the formiojs dependency

- package-lock.json
- package.json
This PR updates the `jquery` dependency.
> Updates the jquery dependency

- package-lock.json
- package.json
This PR updates the `keycloak-js` dependency.
> Updates the keycloak-js dependency

- src/components/Buttons/ClaimUnclaimTask.test.jsx
- src/components/Headers/Header.jsx
- src/components/Headers/Header.test.jsx
- src/components/Tabs/Tabs.jsx
- src/routes/TaskList/__test__/TaskListPage.Airpax.test.jsx
- src/routes/TaskList/__test__/TaskListPage.RoRo.test.jsx
- src/routes/TaskList/components/shared/TargetIndicatorsSection.test.jsx
- src/routes/TaskList/constants.js
- src/routes/index.jsx
- src/routes/roro/TaskLists/TaskListPage.jsx
- src/utils/Common/commonUtil.js
- src/utils/Common/commonUtil.test.js
- src/utils/constants.js
Fixes bug where tab selection was not retained for RoRo v2 task list after going back to task list from details page.
> Tab selection fix

- src/components/Buttons/ClaimTaskButton.test.jsx
- src/components/Headers/TaskManagementHeader.jsx
- src/components/Headers/TaskManagementHeader.test.jsx
- src/components/Tabs/Tabs.jsx
- src/context/TaskSelectedTabContext.jsx
- src/routes/TaskDetails/TaskVersions.test.jsx
- src/routes/TaskList/TaskListPage.jsx
- src/routes/TaskList/__test__/TaskListPage.Airpax.test.jsx
- src/routes/TaskList/__test__/TaskListPage.RoRo.test.jsx
- src/routes/roro/__tests__/TaskListPage.test.jsx
- src/routes/roro/__tests__/TaskListPageFilters.test.jsx
- src/utils/Common/commonUtil.js
- src/utils/Common/commonUtil.test.js
- src/utils/constants.js
This PR fixes a bug where the task status would be incorrectly set when going from task details page back to the task list page.
This PR removes code left over from the removal of the PNR data tab in task details.
> COP-10620 - Task status bug

- src/routes/TaskDetails/TaskDetailsPage.jsx
- src/routes/TaskDetails/TaskDetailsPage.test.jsx
Showing an error message for tasks that have been achieved
1. Find or create a task in dev. It will need to be an airpax task
2. Use POST /v2/targeting-tasks/archive?task-id=DEV-20220905-926
3. Reload the task details page for that task and it should've disappeared
\* Required
> COP-11782: Showing an error message for tasks that have been archived

- src/forms/filters.js
Removes the unfinished movement direction filter enabled by accident.
> Removes the unfinished movement direction filter

- src/routes/roro/TaskDetails/TaskVersionsMode/SectionRenderer.jsx
This PR updates the constant reference used when formatting occupant's dob & document expiry dates.
> COP-11951 - Occupants Dob

- src/components/Filter/Custom/Filter.jsx
- src/components/Filter/Custom/Filter.test.jsx
- src/components/Filter/Custom/getFilter.jsx
- src/components/Filter/helper/setupCounts.js
- src/forms/filters.js
- src/routes/TaskList/TaskListPage.jsx
- src/routes/TaskList/__test__/TaskListPage.Airpax.test.jsx
- src/routes/TaskList/__test__/TaskListPage.RoRo.test.jsx
- src/routes/TaskList/constants.js
- src/utils/constants.js
User can filters the tasks by flight status for Air Passengers
\* Required
> COP-10856: Implemented filters by flight status
